const path = require('path'); const crypto = require('crypto'); const bcrypt = require('bcryptjs'); const { Pool } = require('pg');
require('dotenv').config({ path: path.resolve(__dirname, '../../.env'), quiet: true });
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const canonicalize = value => Array.isArray(value) ? value.map(canonicalize) : value && typeof value === 'object' && !(value instanceof Date) ? Object.keys(value).sort().reduce((out,key)=>{out[key]=canonicalize(value[key]);return out;},{}) : value instanceof Date ? value.toISOString() : value;
const digest = value => crypto.createHash('sha256').update(JSON.stringify(canonicalize(value))).digest('hex');
async function audit(client, tenantId, eventType, entityType, entityId, eventData) { await client.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`audit:${tenantId}`]); const latest=(await client.query('SELECT tenant_sequence,event_hash FROM tsc_audit_events WHERE tenant_id=$1 ORDER BY tenant_sequence DESC LIMIT 1',[tenantId])).rows[0]; const sequence=Number(latest?.tenant_sequence||0)+1; const previousHash=latest?.event_hash||'0'.repeat(64); const occurredAt=new Date(); const eventHash=digest({tenantId,sequence,eventType,entityType,entityId,actorUserId:null,requestId:null,eventData,previousHash,occurredAt:occurredAt.toISOString()}); await client.query(`INSERT INTO tsc_audit_events(id,tenant_id,tenant_sequence,event_type,entity_type,entity_id,event_data,previous_hash,event_hash,occurred_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[crypto.randomUUID(),tenantId,sequence,eventType,entityType,entityId,eventData,previousHash,eventHash,occurredAt]); }
async function main() {
  const [tenantSlugRaw, tenantNameRaw, emailRaw, roleRaw, userNameRaw, serviceSourceRaw, serviceInstrumentRaw] = process.argv.slice(2); const password = process.env.TETRASCIENCE_INITIAL_PASSWORD;
  const tenantSlug = tenantSlugRaw?.trim().toLowerCase(); const tenantName = tenantNameRaw?.trim(); const email = emailRaw?.trim().toLowerCase(); const role = roleRaw?.trim().toUpperCase(); const userName = userNameRaw?.trim();
  const serviceSource = serviceSourceRaw?.trim() || null; const serviceInstrument = serviceInstrumentRaw?.trim() || null;
  if (!tenantSlug || !/^[a-z0-9][a-z0-9-]{1,78}[a-z0-9]$/.test(tenantSlug) || !tenantName || !email || !['TENANT_ADMIN','SCIENTIST','QUALITY_REVIEWER','INSTRUMENT_SERVICE','AUDITOR'].includes(role) || !userName || !password || password.length < 12 || (role === 'INSTRUMENT_SERVICE' ? (!serviceSource || !serviceInstrument) : (serviceSource || serviceInstrument))) throw new Error("Usage: TETRASCIENCE_INITIAL_PASSWORD='<12+ chars>' npm run user:create -- tenant-slug 'Tenant Name' user@example.com ROLE 'User Name' [service-source instrument-key]");
  const client = await pool.connect(); try { await client.query('BEGIN'); let tenant = (await client.query('SELECT id FROM tsc_tenants WHERE slug=$1', [tenantSlug])).rows[0]; const tenantCreated=!tenant; if (!tenant) { tenant = { id: crypto.randomUUID() }; await client.query(`INSERT INTO tsc_tenants(id,slug,name,status) VALUES ($1,$2,$3,'ACTIVE')`, [tenant.id, tenantSlug, tenantName]); }
    const existing=(await client.query('SELECT id,tenant_id FROM tsc_users WHERE email=$1 FOR UPDATE',[email])).rows[0]; if(existing&&existing.tenant_id!==tenant.id) throw new Error('Refusing to transfer an existing email between tenants');
    const userId=existing?.id||crypto.randomUUID(); const hash = await bcrypt.hash(password, 12); await client.query(`INSERT INTO tsc_users(id,tenant_id,email,password_hash,name,role,service_source_system,service_instrument_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(email) DO UPDATE SET password_hash=EXCLUDED.password_hash,name=EXCLUDED.name,role=EXCLUDED.role,service_source_system=EXCLUDED.service_source_system,service_instrument_key=EXCLUDED.service_instrument_key,active=true`, [userId, tenant.id, email, hash, userName, role, serviceSource, serviceInstrument]); if(tenantCreated) await audit(client,tenant.id,'TENANT_CREATED','TENANT',tenant.id,{slug:tenantSlug,name:tenantName}); await audit(client,tenant.id,existing?'USER_ROTATED':'USER_PROVISIONED','USER',userId,{email,role,serviceSource,serviceInstrument}); await client.query('COMMIT'); console.log(`Provisioned ${email} as ${role} in ${tenantSlug}`);
  } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
}
main().catch(error => { console.error(error.message); process.exitCode = 1; }).finally(() => pool.end());
