import bcrypt from 'bcryptjs'; import { db } from '../../src/core/db'; import { id } from '../../src/core/domain'; import * as service from '../../src/services/assayService'; import { AuthUser } from '../../src/middleware/auth';

let tenantId:string, otherTenantId:string; let admin:AuthUser, scientist:AuthUser, reviewer:AuthUser, instrumentService:AuthUser, otherScientist:AuthUser; let instrumentId:string, runId:string, quarantinedRunId:string; const password='Strong-quality-password-123';
const timestamp=()=>new Date().toISOString();
const packet=(externalRunKey:string,overrides:any={})=>({externalRunKey,capturedAt:timestamp(),protocol:{id:'POTENCY-001',version:'3.1',assayType:'POTENCY',requiredAnalyte:'IL-6',resultUnit:'PERCENT',minimumReplicates:2,lowerBound:80,upperBound:120},measurements:[{sampleCode:'SAMPLE-001',analyte:'IL-6',value:99,unit:'PERCENT',replicate:1,qualifier:'NONE'},{sampleCode:'SAMPLE-001',analyte:'IL-6',value:101,unit:'PERCENT',replicate:2,qualifier:'NONE'}],...overrides});
const envelope=(record:string,payload:any)=>({sourceSystem:'lims-gateway',sourceRecordId:record,instrumentKey:'reader-01',sourceTimestamp:timestamp(),payload});

beforeAll(async()=>{
  await db.query(`TRUNCATE tsc_audit_events,tsc_state_transitions,tsc_review_decisions,tsc_validation_findings,tsc_measurements,tsc_assay_runs,tsc_ingestion_events,tsc_samples,tsc_instruments,tsc_users,tsc_tenants RESTART IDENTITY CASCADE`);
  tenantId=id();otherTenantId=id();await db.query(`INSERT INTO tsc_tenants(id,slug,name,status) VALUES ($1,'acme-labs','Acme Labs','ACTIVE'),($2,'other-labs','Other Labs','ACTIVE')`,[tenantId,otherTenantId]); const hash=await bcrypt.hash(password,4);
  const add=async(email:string,name:string,role:AuthUser['role'],tenant=tenantId):Promise<AuthUser>=>{const serviceSourceSystem=role==='INSTRUMENT_SERVICE'?'lims-gateway':null;const serviceInstrumentKey=role==='INSTRUMENT_SERVICE'?'reader-01':null;const user={id:id(),email,name,role,tenantId:tenant,serviceSourceSystem,serviceInstrumentKey};await db.query(`INSERT INTO tsc_users(id,tenant_id,email,password_hash,name,role,service_source_system,service_instrument_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,[user.id,tenant,email,hash,name,role,serviceSourceSystem,serviceInstrumentKey]);return user;};
  admin=await add('admin@acme.invalid','Admin','TENANT_ADMIN');scientist=await add('scientist@acme.invalid','Scientist','SCIENTIST');reviewer=await add('reviewer@acme.invalid','Reviewer','QUALITY_REVIEWER');instrumentService=await add('instrument@acme.invalid','Instrument Service','INSTRUMENT_SERVICE');otherScientist=await add('scientist@other.invalid','Other Scientist','SCIENTIST',otherTenantId);
}); afterAll(()=>db.end());

test('creates tenant-scoped instrument and sample master data',async()=>{const instrument=await service.createInstrument(admin,{externalKey:'reader-01',sourceSystem:'lims-gateway',name:'Plate Reader 01',instrumentType:'PLATE_READER',serialNumber:'PR-0001',calibratedAt:'2026-07-01T00:00:00Z',calibrationDueAt:'2027-07-01T00:00:00Z',reason:'Qualification package QP-001 approved'});instrumentId=instrument.id;await service.createSample(scientist,{sampleCode:'SAMPLE-001',description:'Reference potency sample',matrix:'serum',reason:'Chain of custody COC-001 received'});expect((await service.dashboard(scientist)).counts).toMatchObject({runs:0,quarantined:0});});

test('ingests and deterministically validates a calibrated assay packet',async()=>{const result=await service.ingest(instrumentService,envelope('event-valid-1',packet('RUN-VALID-1')));expect(result.run?.state).toBe('VALIDATED');expect(result.run?.findings).toEqual([]);runId=result.run!.id;});

test('replays exact source events and rejects conflicting duplicates',async()=>{const original=envelope('event-replay-1',packet('RUN-REPLAY-1'));expect((await service.ingest(instrumentService,original)).replayed).toBe(false);expect((await service.ingest(instrumentService,original)).replayed).toBe(true);await expect(service.ingest(instrumentService,{...original,payload:packet('RUN-CONFLICT')})).rejects.toMatchObject({code:'DUPLICATE_EVENT_CONFLICT',status:409});});

test('rejects an instrument-service identity outside its exact source binding',async()=>{await expect(service.ingest({...instrumentService,serviceInstrumentKey:'reader-02'},envelope('event-wrong-binding',packet('RUN-WRONG-BINDING')))).rejects.toMatchObject({code:'SERVICE_BINDING_MISMATCH',status:403});expect((await db.query(`SELECT count(*)::int count FROM tsc_ingestion_events WHERE source_record_id='event-wrong-binding'`)).rows[0].count).toBe(0);});

test('quarantines protocol unit mismatches with explicit findings',async()=>{const bad=packet('RUN-UNIT-BAD',{measurements:[{sampleCode:'SAMPLE-001',analyte:'IL-6',value:99,unit:'RFU',replicate:1},{sampleCode:'SAMPLE-001',analyte:'IL-6',value:101,unit:'RFU',replicate:2}]});const result=await service.ingest(instrumentService,envelope('event-unit-bad',bad));expect(result.run?.state).toBe('QUARANTINED');expect(result.run?.findings.map(item=>item.code)).toContain('UNIT_MISMATCH');quarantinedRunId=result.run!.id;});

test('persists rejected unknown-sample events for safe retry/correction',async()=>{const bad=packet('RUN-UNKNOWN',{measurements:[{sampleCode:'DOES-NOT-EXIST',analyte:'IL-6',value:99,unit:'PERCENT',replicate:1},{sampleCode:'DOES-NOT-EXIST',analyte:'IL-6',value:100,unit:'PERCENT',replicate:2}]});const rejected=envelope('event-unknown',bad);await expect(service.ingest(instrumentService,rejected)).rejects.toMatchObject({code:'UNKNOWN_OR_INACTIVE_SAMPLE'});expect((await db.query(`SELECT status,error_code FROM tsc_ingestion_events WHERE source_record_id='event-unknown'`)).rows[0]).toEqual({status:'REJECTED',error_code:'UNKNOWN_OR_INACTIVE_SAMPLE'});expect((await service.ingest(instrumentService,rejected)).replayed).toBe(true);});

test('creates correction lineage and withdraws superseded quarantined evidence',async()=>{const result=await service.ingest(instrumentService,envelope('event-correction',packet('RUN-CORRECTED',{revisionOfRunId:quarantinedRunId})));expect(result.run?.state).toBe('VALIDATED');expect((await db.query('SELECT state FROM tsc_assay_runs WHERE id=$1',[quarantinedRunId])).rows[0].state).toBe('WITHDRAWN');});

test('blocks calibrated workflow after an optimistic-version conflict',async()=>{await expect(service.calibrateInstrument(admin,instrumentId,{expectedVersion:99,calibratedAt:'2026-07-20T00:00:00Z',calibrationDueAt:'2027-07-20T00:00:00Z',reason:'Annual calibration'})).rejects.toMatchObject({code:'VERSION_CONFLICT'});expect((await db.query('SELECT version FROM tsc_instruments WHERE id=$1',[instrumentId])).rows[0].version).toBe(1);});

test('quarantines out-of-calibration evidence until an auditable recalibration',async()=>{await service.calibrateInstrument(admin,instrumentId,{expectedVersion:1,calibratedAt:'2025-01-01T00:00:00Z',calibrationDueAt:'2026-01-01T00:00:00Z',reason:'Reconstructed historical calibration window'});const expired=await service.ingest(instrumentService,envelope('event-expired-calibration',packet('RUN-EXPIRED-CAL')));expect(expired.run?.state).toBe('QUARANTINED');expect(expired.run?.findings.map(item=>item.code)).toContain('CALIBRATION_OUT_OF_WINDOW');const recalibrated=await service.calibrateInstrument(admin,instrumentId,{expectedVersion:2,calibratedAt:'2026-07-01T00:00:00Z',calibrationDueAt:'2027-07-01T00:00:00Z',reason:'Calibration certificate CAL-2026-01 verified'});expect(recalibrated.version).toBe(3);});

test('records scientist submission and idempotent quality release with e-signature',async()=>{const submission={clientDecisionId:'scientist-submit-1',reason:'Replicates and protocol evidence reviewed'};expect((await service.submitRun(scientist,runId,submission)).state).toBe('SUBMITTED');expect((await service.submitRun(scientist,runId,submission)).replayed).toBe(true);await expect(service.submitRun(scientist,runId,{...submission,reason:'Different submission content'})).rejects.toMatchObject({code:'DECISION_ID_CONFLICT'});await expect(service.releaseRun({...scientist,role:'QUALITY_REVIEWER'},runId,{clientDecisionId:'self-release',decision:'APPROVE',reason:'Attempted self release',password})).rejects.toMatchObject({code:'SEPARATION_OF_DUTIES'});await expect(service.releaseRun(reviewer,runId,{clientDecisionId:'quality-release-1',decision:'APPROVE',reason:'Quality checks completed',password:'Wrong-password-value'})).rejects.toMatchObject({code:'E_SIGNATURE_FAILED'});const release={clientDecisionId:'quality-release-1',decision:'APPROVE',reason:'Quality checks and source evidence completed',password};expect((await service.releaseRun(reviewer,runId,release)).state).toBe('RELEASED');expect((await service.releaseRun(reviewer,runId,release)).replayed).toBe(true);await expect(service.releaseRun(reviewer,runId,{...release,decision:'REJECT',reason:'Different decision content'})).rejects.toMatchObject({code:'DECISION_ID_CONFLICT'});});

test('enforces tenant isolation on assay evidence',async()=>{await expect(service.evidence(otherScientist,runId)).rejects.toMatchObject({code:'RUN_NOT_FOUND',status:404});expect((await service.dashboard(otherScientist)).runs).toHaveLength(0);});

test('returns complete released evidence and immutable decisions',async()=>{const evidence=await service.evidence(scientist,runId);expect(evidence.measurements).toHaveLength(2);expect(evidence.decisions.map((item:any)=>item.stage)).toEqual(['SCIENTIST_SUBMISSION','QUALITY_RELEASE']);await expect(db.query(`UPDATE tsc_measurements SET value=0 WHERE assay_run_id=$1`,[runId])).rejects.toThrow(/append-only/);await expect(db.query(`DELETE FROM tsc_review_decisions WHERE assay_run_id=$1`,[runId])).rejects.toThrow(/append-only/);});

test('verifies the tenant audit hash chain',async()=>expect(await service.verifyAudit(admin)).toMatchObject({valid:true,events:expect.any(Number),lastHash:expect.stringMatching(/^[a-f0-9]{64}$/)}));
