import dotenv from 'dotenv';
import path from 'path';
dotenv.config({ path: path.resolve(__dirname, '../../../.env') });

import bcrypt from 'bcryptjs';
import {
  sequelize,
  Tenant,
  Role,
  User,
  Molecule,
  AssayResult,
  Document,
  KnowledgeNode,
  KnowledgeEdge,
  Entity,
  Pipeline,
  Instrument,
  SearchQuery,
  Embedding,
  AuditLog,
} from '../models';

async function seed() {
  try {
    console.log('Connecting to database...');
    await sequelize.authenticate();
    console.log('Database connected. Dropping and recreating tables...');
    await sequelize.sync({ force: true });
    console.log('Tables recreated successfully.\n');

    // ========== 1. TENANTS (5) ==========
    const tenants = await Tenant.bulkCreate([
      {
        name: 'AstraZeneca R&D',
        slug: 'astrazeneca-rd',
        industry: 'pharma',
        plan: 'enterprise',
        status: 'active',
        dataIsolation: 'full',
        maxUsers: 500,
        maxStorage: 10000,
        contactEmail: 'admin@astrazeneca-rd.com',
        contactName: 'Sarah Chen',
        settings: { theme: 'light', notifications: true, twoFactor: true },
      },
      {
        name: 'Novartis Discovery',
        slug: 'novartis-discovery',
        industry: 'pharma',
        plan: 'enterprise',
        status: 'active',
        dataIsolation: 'full',
        maxUsers: 300,
        maxStorage: 8000,
        contactEmail: 'ops@novartis-discovery.com',
        contactName: 'Marcus Weber',
        settings: { theme: 'dark', notifications: true, twoFactor: true },
      },
      {
        name: 'Amgen Biologics',
        slug: 'amgen-biologics',
        industry: 'biotech',
        plan: 'enterprise',
        status: 'active',
        dataIsolation: 'full',
        maxUsers: 200,
        maxStorage: 5000,
        contactEmail: 'it@amgen-biologics.com',
        contactName: 'Jennifer Park',
        settings: { theme: 'light', notifications: true, twoFactor: false },
      },
      {
        name: 'GeneTech CRO',
        slug: 'genetech-cro',
        industry: 'cro',
        plan: 'professional',
        status: 'active',
        dataIsolation: 'shared',
        maxUsers: 100,
        maxStorage: 2000,
        contactEmail: 'admin@genetech-cro.com',
        contactName: 'David Kim',
        settings: { theme: 'light', notifications: true, twoFactor: false },
      },
      {
        name: 'MIT Pharma Lab',
        slug: 'mit-pharma-lab',
        industry: 'academic',
        plan: 'starter',
        status: 'trial',
        dataIsolation: 'hybrid',
        maxUsers: 25,
        maxStorage: 500,
        contactEmail: 'lab@mit-pharma.edu',
        contactName: 'Prof. Emily Rodriguez',
        settings: { theme: 'light', notifications: false, twoFactor: false },
      },
      {
        name: 'Roche Diagnostics',
        slug: 'roche-diagnostics',
        industry: 'pharma',
        plan: 'enterprise',
        status: 'active',
        dataIsolation: 'full',
        maxUsers: 400,
        maxStorage: 9000,
        contactEmail: 'admin@roche-dx.com',
        contactName: 'Hans Mueller',
        settings: { theme: 'light', notifications: true, twoFactor: true },
      },
      {
        name: 'Pfizer Oncology',
        slug: 'pfizer-oncology',
        industry: 'pharma',
        plan: 'enterprise',
        status: 'active',
        dataIsolation: 'full',
        maxUsers: 350,
        maxStorage: 7500,
        contactEmail: 'it@pfizer-onc.com',
        contactName: 'Lisa Wang',
        settings: { theme: 'dark', notifications: true, twoFactor: true },
      },
      {
        name: 'Merck Research Labs',
        slug: 'merck-research',
        industry: 'pharma',
        plan: 'enterprise',
        status: 'active',
        dataIsolation: 'full',
        maxUsers: 250,
        maxStorage: 6000,
        contactEmail: 'labs@merck-research.com',
        contactName: 'Robert Johnson',
        settings: { theme: 'light', notifications: true, twoFactor: true },
      },
      {
        name: 'BioNTech mRNA',
        slug: 'biontech-mrna',
        industry: 'biotech',
        plan: 'professional',
        status: 'active',
        dataIsolation: 'shared',
        maxUsers: 150,
        maxStorage: 3000,
        contactEmail: 'ops@biontech-mrna.com',
        contactName: 'Anna Schmidt',
        settings: { theme: 'light', notifications: true, twoFactor: false },
      },
      {
        name: 'Moderna Therapeutics',
        slug: 'moderna-tx',
        industry: 'biotech',
        plan: 'enterprise',
        status: 'active',
        dataIsolation: 'full',
        maxUsers: 300,
        maxStorage: 8000,
        contactEmail: 'admin@moderna-tx.com',
        contactName: 'Michael Brown',
        settings: { theme: 'dark', notifications: true, twoFactor: true },
      },
      {
        name: 'Stanford Chem Bio',
        slug: 'stanford-chembio',
        industry: 'academic',
        plan: 'starter',
        status: 'active',
        dataIsolation: 'hybrid',
        maxUsers: 50,
        maxStorage: 1000,
        contactEmail: 'lab@stanford-chembio.edu',
        contactName: 'Prof. James Wilson',
        settings: { theme: 'light', notifications: false, twoFactor: false },
      },
      {
        name: 'Covance CRO Services',
        slug: 'covance-cro',
        industry: 'cro',
        plan: 'professional',
        status: 'active',
        dataIsolation: 'shared',
        maxUsers: 120,
        maxStorage: 2500,
        contactEmail: 'support@covance-cro.com',
        contactName: 'Patricia Davis',
        settings: { theme: 'light', notifications: true, twoFactor: true },
      },
      {
        name: 'Gilead Sciences',
        slug: 'gilead-sciences',
        industry: 'pharma',
        plan: 'enterprise',
        status: 'active',
        dataIsolation: 'full',
        maxUsers: 200,
        maxStorage: 5000,
        contactEmail: 'it@gilead.com',
        contactName: 'Kevin Lee',
        settings: { theme: 'light', notifications: true, twoFactor: true },
      },
      {
        name: 'Regeneron Antibodies',
        slug: 'regeneron-ab',
        industry: 'biotech',
        plan: 'professional',
        status: 'active',
        dataIsolation: 'shared',
        maxUsers: 180,
        maxStorage: 4000,
        contactEmail: 'ops@regeneron-ab.com',
        contactName: 'Susan Martinez',
        settings: { theme: 'dark', notifications: true, twoFactor: false },
      },
      {
        name: 'Sanofi Vaccines',
        slug: 'sanofi-vaccines',
        industry: 'pharma',
        plan: 'enterprise',
        status: 'active',
        dataIsolation: 'full',
        maxUsers: 280,
        maxStorage: 6500,
        contactEmail: 'admin@sanofi-vax.com',
        contactName: 'Pierre Dubois',
        settings: { theme: 'light', notifications: true, twoFactor: true },
      },
      {
        name: 'Oxford BioMedica',
        slug: 'oxford-biomed',
        industry: 'academic',
        plan: 'professional',
        status: 'trial',
        dataIsolation: 'hybrid',
        maxUsers: 75,
        maxStorage: 1500,
        contactEmail: 'research@oxford-biomed.ac.uk',
        contactName: 'Dr. Elizabeth Taylor',
        settings: { theme: 'light', notifications: false, twoFactor: false },
      },
    ]);
    console.log(`Seeded ${tenants.length} Tenants`);

    // ========== 2. ROLES (4) ==========
    const roles = await Role.bulkCreate([
      {
        name: 'Admin',
        permissions: {
          molecules: ['create', 'read', 'update', 'delete'],
          assays: ['create', 'read', 'update', 'delete'],
          documents: ['create', 'read', 'update', 'delete'],
          pipelines: ['create', 'read', 'update', 'delete'],
          instruments: ['create', 'read', 'update', 'delete'],
          users: ['create', 'read', 'update', 'delete'],
          tenants: ['create', 'read', 'update', 'delete'],
          auditLogs: ['read'],
          ai: ['analyze', 'extract', 'summarize'],
        },
        tenantId: tenants[0].id,
        description: 'Full administrative access to all platform features',
        isSystem: true,
      },
      {
        name: 'Scientist',
        permissions: {
          molecules: ['create', 'read', 'update'],
          assays: ['create', 'read', 'update'],
          documents: ['create', 'read', 'update'],
          pipelines: ['read'],
          instruments: ['read'],
          users: ['read'],
          auditLogs: ['read'],
          ai: ['analyze', 'extract', 'summarize'],
        },
        tenantId: tenants[0].id,
        description: 'Research scientist with access to scientific data and AI tools',
        isSystem: true,
      },
      {
        name: 'Engineer',
        permissions: {
          molecules: ['read'],
          assays: ['read'],
          documents: ['read'],
          pipelines: ['create', 'read', 'update', 'delete'],
          instruments: ['create', 'read', 'update', 'delete'],
          users: ['read'],
          auditLogs: ['read'],
          ai: ['analyze'],
        },
        tenantId: tenants[0].id,
        description: 'Data engineer with pipeline and instrument management access',
        isSystem: true,
      },
      {
        name: 'Viewer',
        permissions: {
          molecules: ['read'],
          assays: ['read'],
          documents: ['read'],
          pipelines: ['read'],
          instruments: ['read'],
          users: [],
          auditLogs: [],
          ai: [],
        },
        tenantId: tenants[0].id,
        description: 'Read-only access to scientific data',
        isSystem: true,
      },
    ]);
    console.log(`Seeded ${roles.length} Roles`);

    // ========== 3. USERS (5) ==========
    const hashedPassword = await bcrypt.hash('password123', 10);
    const users = await User.bulkCreate([
      {
        email: 'admin@tetrascience.io',
        password: hashedPassword,
        name: 'Alex Thompson',
        role: 'admin',
        tenantId: tenants[0].id,
        avatar: null,
        lastLogin: new Date('2026-04-01T10:30:00Z'),
        isActive: true,
      },
      {
        email: 'scientist@tetrascience.io',
        password: hashedPassword,
        name: 'Dr. Maria Santos',
        role: 'scientist',
        tenantId: tenants[0].id,
        avatar: null,
        lastLogin: new Date('2026-04-01T09:15:00Z'),
        isActive: true,
      },
      {
        email: 'engineer@tetrascience.io',
        password: hashedPassword,
        name: 'James Liu',
        role: 'engineer',
        tenantId: tenants[1].id,
        avatar: null,
        lastLogin: new Date('2026-03-31T16:45:00Z'),
        isActive: true,
      },
      {
        email: 'viewer@tetrascience.io',
        password: hashedPassword,
        name: 'Rachel Green',
        role: 'viewer',
        tenantId: tenants[2].id,
        avatar: null,
        lastLogin: new Date('2026-03-30T14:20:00Z'),
        isActive: true,
      },
      {
        email: 'researcher@tetrascience.io',
        password: hashedPassword,
        name: 'Prof. Kenji Tanaka',
        role: 'scientist',
        tenantId: tenants[4].id,
        avatar: null,
        lastLogin: new Date('2026-04-01T08:00:00Z'),
        isActive: true,
      },
      {
        email: 'hans.mueller@roche-dx.com',
        password: hashedPassword,
        name: 'Hans Mueller',
        role: 'admin',
        tenantId: tenants[5].id,
        avatar: null,
        lastLogin: new Date('2026-04-01T07:30:00Z'),
        isActive: true,
      },
      {
        email: 'lisa.wang@pfizer-onc.com',
        password: hashedPassword,
        name: 'Lisa Wang',
        role: 'scientist',
        tenantId: tenants[6].id,
        avatar: null,
        lastLogin: new Date('2026-03-31T12:00:00Z'),
        isActive: true,
      },
      {
        email: 'robert.j@merck.com',
        password: hashedPassword,
        name: 'Robert Johnson',
        role: 'engineer',
        tenantId: tenants[7].id,
        avatar: null,
        lastLogin: new Date('2026-03-30T15:20:00Z'),
        isActive: true,
      },
      {
        email: 'anna.s@biontech.com',
        password: hashedPassword,
        name: 'Anna Schmidt',
        role: 'scientist',
        tenantId: tenants[8].id,
        avatar: null,
        lastLogin: new Date('2026-04-01T11:00:00Z'),
        isActive: true,
      },
      {
        email: 'michael.b@moderna.com',
        password: hashedPassword,
        name: 'Michael Brown',
        role: 'admin',
        tenantId: tenants[9].id,
        avatar: null,
        lastLogin: new Date('2026-03-29T09:45:00Z'),
        isActive: true,
      },
      {
        email: 'j.wilson@stanford.edu',
        password: hashedPassword,
        name: 'Prof. James Wilson',
        role: 'scientist',
        tenantId: tenants[10].id,
        avatar: null,
        lastLogin: new Date('2026-04-01T06:30:00Z'),
        isActive: true,
      },
      {
        email: 'patricia.d@covance.com',
        password: hashedPassword,
        name: 'Patricia Davis',
        role: 'engineer',
        tenantId: tenants[11].id,
        avatar: null,
        lastLogin: new Date('2026-03-31T10:15:00Z'),
        isActive: true,
      },
      {
        email: 'kevin.lee@gilead.com',
        password: hashedPassword,
        name: 'Kevin Lee',
        role: 'scientist',
        tenantId: tenants[12].id,
        avatar: null,
        lastLogin: new Date('2026-04-01T13:00:00Z'),
        isActive: true,
      },
      {
        email: 'susan.m@regeneron.com',
        password: hashedPassword,
        name: 'Susan Martinez',
        role: 'scientist',
        tenantId: tenants[13].id,
        avatar: null,
        lastLogin: new Date('2026-03-28T16:30:00Z'),
        isActive: true,
      },
      {
        email: 'pierre.d@sanofi.com',
        password: hashedPassword,
        name: 'Pierre Dubois',
        role: 'admin',
        tenantId: tenants[14].id,
        avatar: null,
        lastLogin: new Date('2026-03-31T08:45:00Z'),
        isActive: true,
      },
      {
        email: 'e.taylor@oxford.ac.uk',
        password: hashedPassword,
        name: 'Dr. Elizabeth Taylor',
        role: 'scientist',
        tenantId: tenants[15].id,
        avatar: null,
        lastLogin: new Date('2026-04-01T14:30:00Z'),
        isActive: true,
      },
    ]);
    console.log(`Seeded ${users.length} Users`);

    // ========== 4. MOLECULES (18) ==========
    const molecules = await Molecule.bulkCreate([
      {
        name: 'Imatinib',
        smiles: 'CC1=C(C=C(C=C1)NC(=O)C2=CC=C(C=C2)CN3CCN(CC3)C)NC4=NC=CC(=N4)C5=CN=CC=C5',
        molecularFormula: 'C29H31N7O',
        molecularWeight: 493.60,
        logP: 3.5,
        hbdCount: 2,
        hbaCount: 7,
        rotatableBonds: 7,
        tpsa: 86.28,
        category: 'small_molecule',
        targetProtein: 'BCR-ABL',
        mechanism: 'Tyrosine kinase inhibitor',
        status: 'active',
        synonyms: 'Gleevec, STI-571',
        description: 'First-generation BCR-ABL tyrosine kinase inhibitor used in CML treatment',
        source: 'ChEMBL',
      },
      {
        name: 'Erlotinib',
        smiles: 'COCCOC1=C(C=C2C(=C1)C(=NC=N2)NC3=CC=CC(=C3)C#C)OCCOC',
        molecularFormula: 'C22H23N3O4',
        molecularWeight: 393.44,
        logP: 3.3,
        hbdCount: 1,
        hbaCount: 6,
        rotatableBonds: 10,
        tpsa: 74.73,
        category: 'small_molecule',
        targetProtein: 'EGFR',
        mechanism: 'EGFR tyrosine kinase inhibitor',
        status: 'active',
        synonyms: 'Tarceva, OSI-774',
        description: 'EGFR inhibitor used in non-small cell lung cancer and pancreatic cancer',
        source: 'ChEMBL',
      },
      {
        name: 'Vemurafenib',
        smiles: 'CCCS(=O)(=O)NC1=CC(=C(C=C1F)C(=O)C2=CNC3=NC=C(C=C23)C4=CC=C(C=C4)Cl)F',
        molecularFormula: 'C23H18ClF2N3O3S',
        molecularWeight: 489.92,
        logP: 4.1,
        hbdCount: 2,
        hbaCount: 5,
        rotatableBonds: 5,
        tpsa: 100.72,
        category: 'small_molecule',
        targetProtein: 'BRAF V600E',
        mechanism: 'BRAF kinase inhibitor',
        status: 'active',
        synonyms: 'Zelboraf, PLX4032',
        description: 'Selective BRAF V600E inhibitor for metastatic melanoma',
        source: 'PubChem',
      },
      {
        name: 'Olaparib',
        smiles: 'O=C(C1CC1)N2CCN(CC2)C(=O)C3=C(C=CC=C3)CC4=NNC(=O)C5=CC=CC=C54',
        molecularFormula: 'C24H23FN3O3',
        molecularWeight: 434.46,
        logP: 1.9,
        hbdCount: 1,
        hbaCount: 5,
        rotatableBonds: 5,
        tpsa: 74.39,
        category: 'small_molecule',
        targetProtein: 'PARP1/PARP2',
        mechanism: 'PARP inhibitor',
        status: 'active',
        synonyms: 'Lynparza, AZD2281',
        description: 'PARP inhibitor for BRCA-mutated ovarian and breast cancer',
        source: 'ChEMBL',
      },
      {
        name: 'Pembrolizumab',
        smiles: 'Protein-based',
        molecularFormula: 'C6504H10004N1716O2036S46',
        molecularWeight: 146300.0,
        logP: null,
        hbdCount: null,
        hbaCount: null,
        rotatableBonds: null,
        tpsa: null,
        category: 'antibody',
        targetProtein: 'PD-1',
        mechanism: 'PD-1 checkpoint inhibitor',
        status: 'active',
        synonyms: 'Keytruda, MK-3475',
        description: 'Anti-PD-1 monoclonal antibody for multiple cancer types',
        source: 'DrugBank',
      },
      {
        name: 'Trastuzumab',
        smiles: 'Protein-based',
        molecularFormula: 'C6470H10012N1726O2013S42',
        molecularWeight: 145531.5,
        logP: null,
        hbdCount: null,
        hbaCount: null,
        rotatableBonds: null,
        tpsa: null,
        category: 'antibody',
        targetProtein: 'HER2',
        mechanism: 'HER2 receptor antagonist',
        status: 'active',
        synonyms: 'Herceptin',
        description: 'Anti-HER2 monoclonal antibody for HER2-positive breast cancer',
        source: 'DrugBank',
      },
      {
        name: 'Semaglutide',
        smiles: 'Peptide-based',
        molecularFormula: 'C187H291N45O59',
        molecularWeight: 4113.58,
        logP: null,
        hbdCount: null,
        hbaCount: null,
        rotatableBonds: null,
        tpsa: null,
        category: 'peptide',
        targetProtein: 'GLP-1R',
        mechanism: 'GLP-1 receptor agonist',
        status: 'active',
        synonyms: 'Ozempic, Wegovy',
        description: 'GLP-1 receptor agonist for type 2 diabetes and obesity',
        source: 'DrugBank',
      },
      {
        name: 'Osimertinib',
        smiles: 'COC1=C(C=C2C(=C1)N=CN=C2NC3=CC(=C(C=C3)F)Cl)NC(=O)C=C',
        molecularFormula: 'C28H33N7O2',
        molecularWeight: 499.62,
        logP: 3.4,
        hbdCount: 3,
        hbaCount: 7,
        rotatableBonds: 9,
        tpsa: 87.59,
        category: 'small_molecule',
        targetProtein: 'EGFR T790M',
        mechanism: 'Third-generation EGFR inhibitor',
        status: 'active',
        synonyms: 'Tagrisso, AZD9291',
        description: 'Third-generation EGFR-TKI targeting T790M resistance mutation',
        source: 'ChEMBL',
      },
      {
        name: 'Venetoclax',
        smiles: 'CC1(CCC(=C(C1)C2=CC=C(C=C2)Cl)CN3CCN(CC3)C4=CC(=C(C=C4)C(=O)NS(=O)(=O)C5=CC(=C(C=C5)[N+](=O)[O-])OC6CCCC6)OC)C',
        molecularFormula: 'C46H50ClN7O7S',
        molecularWeight: 868.44,
        logP: 8.1,
        hbdCount: 3,
        hbaCount: 11,
        rotatableBonds: 14,
        tpsa: 183.2,
        category: 'small_molecule',
        targetProtein: 'BCL-2',
        mechanism: 'BCL-2 inhibitor',
        status: 'active',
        synonyms: 'Venclexta, ABT-199',
        description: 'Selective BCL-2 inhibitor for CLL and AML',
        source: 'ChEMBL',
      },
      {
        name: 'Larotrectinib',
        smiles: 'OC1CCN(C1)C(=O)C2=CNN3C(=CC=C23)C4=CC=C5N=CN=C5C=C4',
        molecularFormula: 'C21H22FN5O2',
        molecularWeight: 428.44,
        logP: 2.2,
        hbdCount: 2,
        hbaCount: 5,
        rotatableBonds: 3,
        tpsa: 79.93,
        category: 'small_molecule',
        targetProtein: 'TRK A/B/C',
        mechanism: 'Pan-TRK inhibitor',
        status: 'active',
        synonyms: 'Vitrakvi, LOXO-101',
        description: 'Pan-TRK inhibitor for NTRK fusion-positive solid tumors',
        source: 'PubChem',
      },
      {
        name: 'Ruxolitinib',
        smiles: 'N#CC1=CC=C(C=C1)C2=C(C)C3=C(N2)N=CN=C3NC4CCCC(C4)N5CCCC5',
        molecularFormula: 'C17H18N6',
        molecularWeight: 306.37,
        logP: 2.1,
        hbdCount: 1,
        hbaCount: 4,
        rotatableBonds: 4,
        tpsa: 83.18,
        category: 'small_molecule',
        targetProtein: 'JAK1/JAK2',
        mechanism: 'JAK1/JAK2 inhibitor',
        status: 'active',
        synonyms: 'Jakafi, INCB018424',
        description: 'JAK1/JAK2 inhibitor for myelofibrosis and polycythemia vera',
        source: 'ChEMBL',
      },
      {
        name: 'Apalutamide',
        smiles: 'CC(CS(=O)(=O)C)(C1=CC(=C(C=C1)C#N)C(F)(F)F)NC(=O)C2=CC=C(C=C2)N3CCC3=O',
        molecularFormula: 'C21H15F4N3O2S',
        molecularWeight: 477.37,
        logP: 3.7,
        hbdCount: 1,
        hbaCount: 5,
        rotatableBonds: 5,
        tpsa: 93.17,
        category: 'small_molecule',
        targetProtein: 'Androgen Receptor',
        mechanism: 'Androgen receptor antagonist',
        status: 'screening',
        synonyms: 'Erleada, ARN-509',
        description: 'Next-generation androgen receptor inhibitor for prostate cancer',
        source: 'ChEMBL',
      },
      {
        name: 'TS-001',
        smiles: 'CC(C)CC1=CC(=CC(=C1O)C(C)C)C2=CC(=NO2)C(F)(F)F',
        molecularFormula: 'C18H22F3NO2',
        molecularWeight: 341.37,
        logP: 4.5,
        hbdCount: 1,
        hbaCount: 3,
        rotatableBonds: 5,
        tpsa: 46.33,
        category: 'small_molecule',
        targetProtein: 'KRAS G12C',
        mechanism: 'KRAS G12C covalent inhibitor',
        status: 'screening',
        synonyms: null,
        description: 'Novel KRAS G12C covalent inhibitor in early-stage screening',
        source: 'Internal',
      },
      {
        name: 'TS-002',
        smiles: 'O=C(NC1=CC=CC=C1C(F)(F)F)C2=CC3=C(O2)C=CC(=C3)NS(=O)(=O)C',
        molecularFormula: 'C17H13F3N2O4S',
        molecularWeight: 398.36,
        logP: 2.8,
        hbdCount: 2,
        hbaCount: 6,
        rotatableBonds: 5,
        tpsa: 95.13,
        category: 'small_molecule',
        targetProtein: 'CDK4/6',
        mechanism: 'CDK4/6 selective inhibitor',
        status: 'screening',
        synonyms: null,
        description: 'Novel CDK4/6 inhibitor with improved selectivity profile',
        source: 'Internal',
      },
      {
        name: 'Patisiran',
        smiles: 'siRNA-based',
        molecularFormula: 'RNA duplex',
        molecularWeight: 14520.0,
        logP: null,
        hbdCount: null,
        hbaCount: null,
        rotatableBonds: null,
        tpsa: null,
        category: 'nucleic_acid',
        targetProtein: 'TTR mRNA',
        mechanism: 'RNA interference (RNAi)',
        status: 'active',
        synonyms: 'Onpattro',
        description: 'siRNA therapeutic for hereditary transthyretin amyloidosis',
        source: 'DrugBank',
      },
      {
        name: 'Nusinersen',
        smiles: 'ASO-based',
        molecularFormula: 'Modified ASO',
        molecularWeight: 7501.0,
        logP: null,
        hbdCount: null,
        hbaCount: null,
        rotatableBonds: null,
        tpsa: null,
        category: 'nucleic_acid',
        targetProtein: 'SMN2 pre-mRNA',
        mechanism: 'Antisense oligonucleotide splicing modulator',
        status: 'active',
        synonyms: 'Spinraza',
        description: 'ASO that modifies SMN2 splicing for spinal muscular atrophy',
        source: 'DrugBank',
      },
      {
        name: 'TS-003',
        smiles: 'CC1=CC=C(C=C1)C2=CC(=NN2C3=CC=C(C=C3)S(N)(=O)=O)C(F)(F)F',
        molecularFormula: 'C17H14F3N3O2S',
        molecularWeight: 381.37,
        logP: 3.2,
        hbdCount: 1,
        hbaCount: 4,
        rotatableBonds: 4,
        tpsa: 86.39,
        category: 'small_molecule',
        targetProtein: 'STING',
        mechanism: 'STING agonist',
        status: 'screening',
        synonyms: null,
        description: 'Novel STING agonist for immuno-oncology applications',
        source: 'Internal',
      },
      {
        name: 'Palbociclib',
        smiles: 'CC(=O)C1=C(C(=O)N(C(=O)N1C2CCCC2)C3=C(C=C(C=C3)NC4=NC=C(C(=N4)C)N5CCNCC5)F)C',
        molecularFormula: 'C24H29N7O2',
        molecularWeight: 447.54,
        logP: 2.7,
        hbdCount: 2,
        hbaCount: 7,
        rotatableBonds: 5,
        tpsa: 103.55,
        category: 'small_molecule',
        targetProtein: 'CDK4/CDK6',
        mechanism: 'CDK4/6 inhibitor',
        status: 'active',
        synonyms: 'Ibrance, PD-0332991',
        description: 'CDK4/6 inhibitor for HR+/HER2- metastatic breast cancer',
        source: 'ChEMBL',
      },
    ]);
    console.log(`Seeded ${molecules.length} Molecules`);

    // ========== 5. ASSAY RESULTS (20) ==========
    const assays = await AssayResult.bulkCreate([
      { assayName: 'BCR-ABL Kinase IC50', assayType: 'binding', moleculeId: molecules[0].id, targetProtein: 'BCR-ABL', result: 0.025, unit: 'uM', concentration: 10, concentrationUnit: 'uM', plateId: 'PLT-2026-001', wellPosition: 'A01', operator: 'Dr. Santos', runDate: new Date('2026-03-15'), status: 'validated', notes: 'Excellent potency against BCR-ABL wild-type' },
      { assayName: 'EGFR Binding Assay', assayType: 'binding', moleculeId: molecules[1].id, targetProtein: 'EGFR', result: 0.002, unit: 'uM', concentration: 1, concentrationUnit: 'uM', plateId: 'PLT-2026-002', wellPosition: 'B03', operator: 'Dr. Santos', runDate: new Date('2026-03-16'), status: 'validated', notes: 'Potent EGFR inhibition confirmed' },
      { assayName: 'BRAF V600E Selectivity', assayType: 'binding', moleculeId: molecules[2].id, targetProtein: 'BRAF V600E', result: 0.031, unit: 'uM', concentration: 5, concentrationUnit: 'uM', plateId: 'PLT-2026-003', wellPosition: 'C05', operator: 'James Liu', runDate: new Date('2026-03-17'), status: 'validated', notes: 'Selective for V600E over wild-type BRAF' },
      { assayName: 'PARP1 Enzyme Inhibition', assayType: 'functional', moleculeId: molecules[3].id, targetProtein: 'PARP1', result: 0.005, unit: 'uM', concentration: 1, concentrationUnit: 'uM', plateId: 'PLT-2026-004', wellPosition: 'D07', operator: 'Dr. Santos', runDate: new Date('2026-03-18'), status: 'validated', notes: 'Strong PARP trapping activity observed' },
      { assayName: 'PD-1/PD-L1 Blocking', assayType: 'functional', moleculeId: molecules[4].id, targetProtein: 'PD-1', result: 0.29, unit: 'nM', concentration: 100, concentrationUnit: 'nM', plateId: 'PLT-2026-005', wellPosition: 'E02', operator: 'Dr. Santos', runDate: new Date('2026-03-19'), status: 'validated', notes: 'Complete PD-1/PD-L1 blockade at tested concentration' },
      { assayName: 'HER2 Receptor Binding', assayType: 'binding', moleculeId: molecules[5].id, targetProtein: 'HER2', result: 5.0, unit: 'nM', concentration: 50, concentrationUnit: 'nM', plateId: 'PLT-2026-006', wellPosition: 'F04', operator: 'Rachel Green', runDate: new Date('2026-03-20'), status: 'validated', notes: 'High-affinity HER2 binding confirmed' },
      { assayName: 'GLP-1R Activation cAMP', assayType: 'functional', moleculeId: molecules[6].id, targetProtein: 'GLP-1R', result: 0.26, unit: 'nM', concentration: 10, concentrationUnit: 'nM', plateId: 'PLT-2026-007', wellPosition: 'G06', operator: 'Prof. Tanaka', runDate: new Date('2026-03-21'), status: 'validated', notes: 'Potent GLP-1R agonism with sustained cAMP elevation' },
      { assayName: 'Microsomal Stability Human', assayType: 'ADME', moleculeId: molecules[0].id, targetProtein: null, result: 78.5, unit: '% remaining', concentration: 1, concentrationUnit: 'uM', plateId: 'PLT-2026-008', wellPosition: 'H01', operator: 'James Liu', runDate: new Date('2026-03-22'), status: 'validated', notes: 'Good metabolic stability in human liver microsomes' },
      { assayName: 'Caco-2 Permeability', assayType: 'ADME', moleculeId: molecules[1].id, targetProtein: null, result: 22.3, unit: '10^-6 cm/s', concentration: 10, concentrationUnit: 'uM', plateId: 'PLT-2026-009', wellPosition: 'A08', operator: 'James Liu', runDate: new Date('2026-03-23'), status: 'validated', notes: 'High permeability indicating good oral absorption' },
      { assayName: 'hERG Inhibition', assayType: 'toxicity', moleculeId: molecules[2].id, targetProtein: 'hERG', result: 15.2, unit: 'uM', concentration: 30, concentrationUnit: 'uM', plateId: 'PLT-2026-010', wellPosition: 'B10', operator: 'Dr. Santos', runDate: new Date('2026-03-24'), status: 'validated', notes: 'Low hERG liability, acceptable safety margin' },
      { assayName: 'A549 Cell Viability', assayType: 'cell_viability', moleculeId: molecules[7].id, targetProtein: 'EGFR T790M', result: 0.015, unit: 'uM', concentration: 1, concentrationUnit: 'uM', plateId: 'PLT-2026-011', wellPosition: 'C12', operator: 'Dr. Santos', runDate: new Date('2026-03-25'), status: 'validated', notes: 'Potent activity in EGFR T790M-mutant NSCLC cell line' },
      { assayName: 'BCL-2 BH3 Mimetic Assay', assayType: 'binding', moleculeId: molecules[8].id, targetProtein: 'BCL-2', result: 0.01, unit: 'nM', concentration: 1, concentrationUnit: 'nM', plateId: 'PLT-2026-012', wellPosition: 'D02', operator: 'Prof. Tanaka', runDate: new Date('2026-03-26'), status: 'validated', notes: 'Sub-nanomolar BCL-2 binding confirmed' },
      { assayName: 'TRK Kinase Panel', assayType: 'binding', moleculeId: molecules[9].id, targetProtein: 'TRKA', result: 0.008, unit: 'uM', concentration: 5, concentrationUnit: 'uM', plateId: 'PLT-2026-013', wellPosition: 'E04', operator: 'Dr. Santos', runDate: new Date('2026-03-27'), status: 'validated', notes: 'Pan-TRK activity confirmed across TRKA, TRKB, TRKC' },
      { assayName: 'JAK2 V617F Selectivity', assayType: 'binding', moleculeId: molecules[10].id, targetProtein: 'JAK2', result: 0.003, unit: 'uM', concentration: 1, concentrationUnit: 'uM', plateId: 'PLT-2026-014', wellPosition: 'F06', operator: 'James Liu', runDate: new Date('2026-03-28'), status: 'validated', notes: 'Potent JAK2 inhibition, acceptable JAK1 selectivity' },
      { assayName: 'KRAS G12C Covalent Binding', assayType: 'binding', moleculeId: molecules[12].id, targetProtein: 'KRAS G12C', result: 0.45, unit: 'uM', concentration: 10, concentrationUnit: 'uM', plateId: 'PLT-2026-015', wellPosition: 'G08', operator: 'Dr. Santos', runDate: new Date('2026-03-29'), status: 'pending', notes: 'Moderate covalent binding, optimization needed' },
      { assayName: 'CDK4/6 Enzymatic Assay', assayType: 'binding', moleculeId: molecules[13].id, targetProtein: 'CDK4', result: 0.018, unit: 'uM', concentration: 5, concentrationUnit: 'uM', plateId: 'PLT-2026-016', wellPosition: 'H10', operator: 'Prof. Tanaka', runDate: new Date('2026-03-30'), status: 'pending', notes: 'Good CDK4 potency, checking CDK6 selectivity' },
      { assayName: 'Hepatocyte Stability Rat', assayType: 'ADME', moleculeId: molecules[12].id, targetProtein: null, result: 45.2, unit: '% remaining', concentration: 1, concentrationUnit: 'uM', plateId: 'PLT-2026-017', wellPosition: 'A03', operator: 'James Liu', runDate: new Date('2026-03-31'), status: 'flagged', notes: 'Low metabolic stability, CYP3A4-mediated clearance suspected' },
      { assayName: 'Ames Mutagenicity', assayType: 'toxicity', moleculeId: molecules[13].id, targetProtein: null, result: 0.0, unit: 'positive_wells', concentration: 100, concentrationUnit: 'uM', plateId: 'PLT-2026-018', wellPosition: 'B05', operator: 'Rachel Green', runDate: new Date('2026-04-01'), status: 'validated', notes: 'Negative in Ames assay, no mutagenic potential' },
      { assayName: 'STING Activation IFN-beta', assayType: 'functional', moleculeId: molecules[16].id, targetProtein: 'STING', result: 1.2, unit: 'uM', concentration: 10, concentrationUnit: 'uM', plateId: 'PLT-2026-019', wellPosition: 'C07', operator: 'Dr. Santos', runDate: new Date('2026-04-01'), status: 'pending', notes: 'Moderate STING activation, dose-dependent IFN-beta induction' },
      { assayName: 'CDK4/6 Cell-Based Proliferation', assayType: 'cell_viability', moleculeId: molecules[17].id, targetProtein: 'CDK4/CDK6', result: 0.011, unit: 'uM', concentration: 1, concentrationUnit: 'uM', plateId: 'PLT-2026-020', wellPosition: 'D09', operator: 'Prof. Tanaka', runDate: new Date('2026-04-01'), status: 'validated', notes: 'Potent antiproliferative activity in MCF-7 cells' },
    ]);
    console.log(`Seeded ${assays.length} AssayResults`);

    // ========== 6. DOCUMENTS (16) ==========
    const documents = await Document.bulkCreate([
      { title: 'SOP-001: High-Throughput Screening Protocol for Kinase Inhibitors', documentType: 'SOP', content: 'This standard operating procedure describes the high-throughput screening methodology for identifying kinase inhibitors using fluorescence-based binding assays. The protocol covers plate preparation, compound dilution series, assay execution, data analysis, and hit identification criteria. All screens are performed in 384-well format using the EnVision plate reader.', abstract: 'Standard operating procedure for kinase inhibitor HTS campaigns', authors: 'Dr. Maria Santos, James Liu', department: 'Drug Discovery', tags: 'HTS,kinase,screening,protocol', version: '3.2', status: 'published', fileSize: 245000, format: 'PDF', tenantId: tenants[0].id },
      { title: 'SOP-002: LC-MS/MS Method for Metabolite Identification', documentType: 'SOP', content: 'Detailed procedure for metabolite identification using liquid chromatography-tandem mass spectrometry. Covers sample preparation from in vitro metabolism studies, chromatographic conditions on the Agilent 6545 Q-TOF, data acquisition parameters, and metabolite identification using Mass Hunter software with molecular feature extraction.', abstract: 'LC-MS/MS methodology for drug metabolite identification', authors: 'James Liu, Dr. Wei Zhang', department: 'DMPK', tags: 'LC-MS,metabolite,ADME,analytical', version: '2.1', status: 'published', fileSize: 312000, format: 'PDF', tenantId: tenants[0].id },
      { title: 'Protocol: EGFR T790M Resistance Mutation Screening Campaign', documentType: 'protocol', content: 'Research protocol for screening compound library against EGFR T790M resistance mutation. Primary screen uses time-resolved FRET-based assay. Confirmed hits proceed to cellular assays in H1975 cells. Counter-screen against wild-type EGFR to determine selectivity index. Target profile: IC50 < 100 nM against T790M with >10x selectivity over WT.', abstract: 'Screening protocol targeting EGFR T790M for next-gen inhibitor discovery', authors: 'Dr. Maria Santos', department: 'Oncology', tags: 'EGFR,T790M,resistance,screening', version: '1.0', status: 'published', fileSize: 178000, format: 'DOCX', tenantId: tenants[0].id },
      { title: 'Protocol: CRISPR-Cas9 Gene Knockout Validation for Target Deconvolution', documentType: 'protocol', content: 'Protocol for validating drug targets using CRISPR-Cas9 gene knockout in cancer cell lines. Includes guide RNA design criteria, lentiviral transduction protocols, puromycin selection, Western blot validation, and phenotypic assessment. Applied to BCL-2, KRAS, and CDK4/6 target validation campaigns.', abstract: 'CRISPR-based target validation protocol for drug discovery', authors: 'Prof. Kenji Tanaka, Dr. Lisa Wang', department: 'Target Biology', tags: 'CRISPR,knockout,target-validation,genomics', version: '1.3', status: 'published', fileSize: 203000, format: 'PDF', tenantId: tenants[4].id },
      { title: 'Quarterly Drug Discovery Report Q1 2026', documentType: 'report', content: 'Summary of Q1 2026 drug discovery activities. Key achievements: 3 compounds advanced to lead optimization, 2 candidates entered IND-enabling studies. Pipeline highlights include TS-001 (KRAS G12C) showing improved metabolic stability after structural optimization, and TS-002 (CDK4/6) demonstrating favorable selectivity in kinome panel. HTS campaign against STING pathway yielded 15 confirmed hits.', abstract: 'Q1 2026 quarterly progress report for drug discovery programs', authors: 'Alex Thompson, Dr. Maria Santos', department: 'R&D Management', tags: 'quarterly-report,pipeline,discovery', version: '1.0', status: 'published', fileSize: 1540000, format: 'PDF', tenantId: tenants[0].id },
      { title: 'Structure-Activity Relationships of BCR-ABL Inhibitors: A Comprehensive Review', documentType: 'publication', content: 'This review examines the structure-activity relationships of BCR-ABL kinase inhibitors from first-generation imatinib through current clinical candidates. Analysis of 150+ compounds reveals key pharmacophoric features including the pyrimidine core, amide linker, and terminal aromatic ring system. Discussion of resistance mutations and strategies for overcoming T315I gatekeeper mutation.', abstract: 'Comprehensive SAR review of BCR-ABL inhibitors spanning three generations', authors: 'Dr. Maria Santos, Prof. Kenji Tanaka', department: 'Medicinal Chemistry', tags: 'SAR,BCR-ABL,kinase,review,CML', version: '1.0', status: 'published', fileSize: 2100000, format: 'PDF', tenantId: tenants[0].id },
      { title: 'Immunotherapy Biomarker Discovery Using Multi-Omics Integration', documentType: 'publication', content: 'We present an integrated multi-omics approach combining transcriptomics, proteomics, and metabolomics data to identify predictive biomarkers for checkpoint immunotherapy response. Analysis of 500 patient samples identified a 12-gene signature predictive of anti-PD-1 response with AUC of 0.89. Key biomarkers include PD-L1 expression, TMB, and a novel metabolic signature.', abstract: 'Multi-omics biomarker discovery for immunotherapy patient stratification', authors: 'Prof. Kenji Tanaka, Dr. Sarah Kim, Dr. James Chen', department: 'Translational Medicine', tags: 'biomarker,immunotherapy,multi-omics,PD-1', version: '1.0', status: 'published', fileSize: 3200000, format: 'PDF', tenantId: tenants[4].id },
      { title: 'SOP-003: Flow Cytometry for Immune Cell Phenotyping', documentType: 'SOP', content: 'Standard operating procedure for multicolor flow cytometry to phenotype immune cell populations. Covers panel design for 12-color analysis, sample preparation from PBMCs and tumor-infiltrating lymphocytes, instrument setup on BD FACSAria III, compensation and gating strategies, and data analysis using FlowJo v10.', abstract: 'Flow cytometry SOP for comprehensive immune cell phenotyping', authors: 'Rachel Green, Dr. Maria Santos', department: 'Immunology', tags: 'flow-cytometry,immunophenotyping,FACS,protocol', version: '2.0', status: 'published', fileSize: 189000, format: 'PDF', tenantId: tenants[2].id },
      { title: 'Regulatory Submission: IND Application for TS-001 KRAS G12C Inhibitor', documentType: 'regulatory', content: 'Investigational New Drug application package for TS-001, a novel covalent KRAS G12C inhibitor. Includes CMC section with synthesis route and analytical characterization, nonclinical pharmacology and toxicology summary, and proposed Phase 1 clinical protocol for advanced solid tumors harboring KRAS G12C mutations.', abstract: 'IND application package for TS-001 KRAS G12C inhibitor program', authors: 'Alex Thompson, Regulatory Affairs Team', department: 'Regulatory Affairs', tags: 'IND,regulatory,KRAS,clinical-trial', version: '1.0', status: 'under_review', fileSize: 15000000, format: 'PDF', tenantId: tenants[0].id },
      { title: 'Patent: Novel Pyrazole Derivatives as STING Agonists for Cancer Immunotherapy', documentType: 'patent', content: 'This invention relates to novel pyrazole-based compounds that activate the STING pathway for cancer immunotherapy. The compounds show potent activation of the cGAS-STING pathway leading to type I interferon production. Preferred embodiments include compounds with IC50 values below 1 micromolar in THP-1 reporter cells. The invention also covers pharmaceutical compositions and methods of treatment.', abstract: 'Patent application covering novel STING agonist compounds', authors: 'Dr. Maria Santos, IP Legal Team', department: 'Intellectual Property', tags: 'patent,STING,immunotherapy,pyrazole', version: '1.0', status: 'draft', fileSize: 890000, format: 'PDF', tenantId: tenants[0].id },
      { title: 'SOP-004: Protein Expression and Purification for Structural Biology', documentType: 'SOP', content: 'Standard operating procedure for recombinant protein expression in E. coli BL21(DE3) and Hi5 insect cells. Covers construct design, expression optimization, cell lysis, affinity chromatography (Ni-NTA and GST), ion exchange, and size exclusion chromatography. Quality control by SDS-PAGE, Western blot, and thermal shift assay.', abstract: 'Protein production SOP for structural biology and biophysics studies', authors: 'Dr. Wei Zhang', department: 'Structural Biology', tags: 'protein-expression,purification,structural-biology', version: '4.0', status: 'published', fileSize: 267000, format: 'PDF', tenantId: tenants[1].id },
      { title: 'Machine Learning Approaches for Drug-Target Interaction Prediction', documentType: 'publication', content: 'We evaluate graph neural networks, transformer architectures, and ensemble methods for predicting drug-target interactions. Our multi-modal model combining molecular graph features with protein language model embeddings achieves AUROC of 0.94 on the BindingDB benchmark. Transfer learning from ChEMBL pre-training improves performance on sparse target classes.', abstract: 'Benchmarking ML models for drug-target interaction prediction', authors: 'James Liu, Prof. Kenji Tanaka', department: 'Computational Biology', tags: 'machine-learning,drug-target,GNN,prediction', version: '1.0', status: 'published', fileSize: 4500000, format: 'PDF', tenantId: tenants[4].id },
      { title: 'Report: Instrument Qualification and Calibration Summary 2026', documentType: 'report', content: 'Annual instrument qualification report covering all analytical instruments in the R&D facility. Includes IQ/OQ/PQ documentation for newly installed Waters UPLC-MS system, recalibration records for existing mass spectrometers, HPLC systems, and NMR spectrometers. All instruments meet GxP compliance requirements per FDA 21 CFR Part 11.', abstract: 'Annual instrument qualification and calibration compliance report', authors: 'James Liu, QA Team', department: 'Quality Assurance', tags: 'qualification,calibration,GxP,compliance', version: '1.0', status: 'published', fileSize: 5600000, format: 'PDF', tenantId: tenants[0].id },
      { title: 'Protocol: In Vivo Efficacy Study for BCL-2 Inhibitor Combination Therapy', documentType: 'protocol', content: 'Preclinical efficacy study protocol evaluating venetoclax in combination with a novel CDK4/6 inhibitor in DLBCL xenograft models. Study design includes 4 arms: vehicle, venetoclax monotherapy, TS-002 monotherapy, and combination. Primary endpoints are tumor volume reduction and overall survival. Secondary endpoints include biomarker analysis.', abstract: 'In vivo combination study protocol for BCL-2 and CDK4/6 inhibitors', authors: 'Dr. Maria Santos, Pharmacology Team', department: 'Pharmacology', tags: 'in-vivo,combination,BCL-2,CDK4/6,xenograft', version: '1.0', status: 'under_review', fileSize: 340000, format: 'DOCX', tenantId: tenants[0].id },
      { title: 'SOP-005: Next-Generation Sequencing Library Preparation and Analysis', documentType: 'SOP', content: 'Standard operating procedure for NGS library preparation using Illumina TruSeq kits. Covers DNA/RNA extraction quality control, library preparation workflow, quality assessment using Bioanalyzer and qPCR, sequencing on NovaSeq 6000, and bioinformatics pipeline for variant calling and gene expression analysis.', abstract: 'NGS library prep and sequencing SOP', authors: 'Prof. Kenji Tanaka, Genomics Core', department: 'Genomics', tags: 'NGS,sequencing,library-prep,genomics', version: '2.5', status: 'published', fileSize: 298000, format: 'PDF', tenantId: tenants[4].id },
      { title: 'Data Integrity Policy and Electronic Records Management', documentType: 'regulatory', content: 'Comprehensive data integrity policy covering electronic records management in compliance with FDA 21 CFR Part 11 and EU Annex 11. Defines requirements for audit trails, electronic signatures, user access controls, data backup and archival procedures, and change control processes. Applies to all computerized systems generating GxP-regulated data.', abstract: 'Data integrity and electronic records compliance policy document', authors: 'Alex Thompson, QA Team, IT Team', department: 'Quality Assurance', tags: 'data-integrity,21-CFR-Part-11,compliance,policy', version: '3.0', status: 'published', fileSize: 156000, format: 'PDF', tenantId: tenants[0].id },
    ]);
    console.log(`Seeded ${documents.length} Documents`);

    // ========== 7. KNOWLEDGE NODES (25) ==========
    const nodes = await KnowledgeNode.bulkCreate([
      { label: 'Imatinib', nodeType: 'compound', properties: { molecularWeight: 493.6, logP: 3.5 }, description: 'First-generation BCR-ABL tyrosine kinase inhibitor', externalId: 'CHEMBL941', source: 'ChEMBL' },
      { label: 'Erlotinib', nodeType: 'compound', properties: { molecularWeight: 393.44, logP: 3.3 }, description: 'EGFR tyrosine kinase inhibitor', externalId: 'CHEMBL553', source: 'ChEMBL' },
      { label: 'Osimertinib', nodeType: 'compound', properties: { molecularWeight: 499.62, logP: 3.4 }, description: 'Third-generation EGFR inhibitor targeting T790M', externalId: 'CHEMBL3353410', source: 'ChEMBL' },
      { label: 'Venetoclax', nodeType: 'compound', properties: { molecularWeight: 868.44, logP: 8.1 }, description: 'Selective BCL-2 inhibitor', externalId: 'CHEMBL3137309', source: 'ChEMBL' },
      { label: 'Pembrolizumab', nodeType: 'compound', properties: { molecularWeight: 146300.0, type: 'antibody' }, description: 'Anti-PD-1 checkpoint inhibitor', externalId: 'DB09037', source: 'DrugBank' },
      { label: 'BCR-ABL', nodeType: 'target', properties: { uniprotId: 'P00519', geneId: 'ABL1' }, description: 'BCR-ABL fusion protein tyrosine kinase', externalId: 'P00519', source: 'UniProt' },
      { label: 'EGFR', nodeType: 'target', properties: { uniprotId: 'P00533', geneId: 'EGFR' }, description: 'Epidermal Growth Factor Receptor', externalId: 'P00533', source: 'UniProt' },
      { label: 'BCL-2', nodeType: 'target', properties: { uniprotId: 'P10415', geneId: 'BCL2' }, description: 'B-cell lymphoma 2 anti-apoptotic protein', externalId: 'P10415', source: 'UniProt' },
      { label: 'PD-1', nodeType: 'target', properties: { uniprotId: 'Q15116', geneId: 'PDCD1' }, description: 'Programmed cell death protein 1', externalId: 'Q15116', source: 'UniProt' },
      { label: 'HER2', nodeType: 'target', properties: { uniprotId: 'P04626', geneId: 'ERBB2' }, description: 'Human epidermal growth factor receptor 2', externalId: 'P04626', source: 'UniProt' },
      { label: 'Chronic Myeloid Leukemia', nodeType: 'disease', properties: { meshId: 'D015464', icdCode: 'C92.1' }, description: 'BCR-ABL positive chronic myelogenous leukemia', externalId: 'DOID:8552', source: 'Disease Ontology' },
      { label: 'Non-Small Cell Lung Cancer', nodeType: 'disease', properties: { meshId: 'D002289', icdCode: 'C34' }, description: 'Most common type of lung cancer', externalId: 'DOID:3908', source: 'Disease Ontology' },
      { label: 'Chronic Lymphocytic Leukemia', nodeType: 'disease', properties: { meshId: 'D015451', icdCode: 'C91.1' }, description: 'B-cell chronic lymphocytic leukemia', externalId: 'DOID:1040', source: 'Disease Ontology' },
      { label: 'Melanoma', nodeType: 'disease', properties: { meshId: 'D008545', icdCode: 'C43' }, description: 'Malignant melanoma of the skin', externalId: 'DOID:1909', source: 'Disease Ontology' },
      { label: 'Breast Cancer HER2+', nodeType: 'disease', properties: { meshId: 'D001943', icdCode: 'C50' }, description: 'HER2-positive breast carcinoma', externalId: 'DOID:0060079', source: 'Disease Ontology' },
      { label: 'MAPK/ERK Pathway', nodeType: 'pathway', properties: { keggId: 'hsa04010' }, description: 'Mitogen-activated protein kinase signaling cascade', externalId: 'R-HSA-5684996', source: 'Reactome' },
      { label: 'PI3K/AKT/mTOR Pathway', nodeType: 'pathway', properties: { keggId: 'hsa04151' }, description: 'Phosphoinositide 3-kinase signaling pathway', externalId: 'R-HSA-1257604', source: 'Reactome' },
      { label: 'Apoptosis Pathway', nodeType: 'pathway', properties: { keggId: 'hsa04210' }, description: 'Programmed cell death signaling', externalId: 'R-HSA-109581', source: 'Reactome' },
      { label: 'PD-L1/PD-1 Checkpoint Pathway', nodeType: 'pathway', properties: { keggId: 'hsa04514' }, description: 'Immune checkpoint signaling pathway', externalId: 'R-HSA-389948', source: 'Reactome' },
      { label: 'ABL1', nodeType: 'gene', properties: { entrezId: '25', chromosome: '9q34.12' }, description: 'ABL proto-oncogene 1, non-receptor tyrosine kinase', externalId: 'ENSG00000097007', source: 'Ensembl' },
      { label: 'EGFR gene', nodeType: 'gene', properties: { entrezId: '1956', chromosome: '7p11.2' }, description: 'Epidermal growth factor receptor gene', externalId: 'ENSG00000146648', source: 'Ensembl' },
      { label: 'BCL2 gene', nodeType: 'gene', properties: { entrezId: '596', chromosome: '18q21.33' }, description: 'BCL2 apoptosis regulator gene', externalId: 'ENSG00000171791', source: 'Ensembl' },
      { label: 'BRAF gene', nodeType: 'gene', properties: { entrezId: '673', chromosome: '7q34' }, description: 'B-Raf proto-oncogene serine/threonine kinase', externalId: 'ENSG00000157764', source: 'Ensembl' },
      { label: 'KRAS gene', nodeType: 'gene', properties: { entrezId: '3845', chromosome: '12p12.1' }, description: 'KRAS proto-oncogene, GTPase', externalId: 'ENSG00000133703', source: 'Ensembl' },
      { label: 'TP53 gene', nodeType: 'gene', properties: { entrezId: '7157', chromosome: '17p13.1' }, description: 'Tumor protein p53, guardian of the genome', externalId: 'ENSG00000141510', source: 'Ensembl' },
    ]);
    console.log(`Seeded ${nodes.length} KnowledgeNodes`);

    // ========== 8. KNOWLEDGE EDGES (30) ==========
    const edges = await KnowledgeEdge.bulkCreate([
      { sourceNodeId: nodes[0].id, targetNodeId: nodes[5].id, relationshipType: 'inhibits', weight: 0.95, evidence: 'Imatinib inhibits BCR-ABL kinase with IC50 of 25 nM', source: 'ChEMBL assay data' },
      { sourceNodeId: nodes[1].id, targetNodeId: nodes[6].id, relationshipType: 'inhibits', weight: 0.92, evidence: 'Erlotinib is a reversible EGFR inhibitor', source: 'FDA label' },
      { sourceNodeId: nodes[2].id, targetNodeId: nodes[6].id, relationshipType: 'inhibits', weight: 0.97, evidence: 'Osimertinib targets EGFR T790M with high selectivity', source: 'Clinical trial data' },
      { sourceNodeId: nodes[3].id, targetNodeId: nodes[7].id, relationshipType: 'inhibits', weight: 0.98, evidence: 'Venetoclax is a highly selective BCL-2 BH3 mimetic', source: 'Crystal structure PDB:6O0K' },
      { sourceNodeId: nodes[4].id, targetNodeId: nodes[8].id, relationshipType: 'targets', weight: 0.96, evidence: 'Pembrolizumab blocks PD-1 receptor', source: 'FDA approval data' },
      { sourceNodeId: nodes[5].id, targetNodeId: nodes[10].id, relationshipType: 'associated_with', weight: 0.99, evidence: 'BCR-ABL fusion drives CML pathogenesis', source: 'Medical literature' },
      { sourceNodeId: nodes[6].id, targetNodeId: nodes[11].id, relationshipType: 'associated_with', weight: 0.85, evidence: 'EGFR mutations found in ~15% of NSCLC', source: 'TCGA genomic data' },
      { sourceNodeId: nodes[7].id, targetNodeId: nodes[12].id, relationshipType: 'associated_with', weight: 0.90, evidence: 'BCL-2 overexpression in CLL promotes survival', source: 'Published literature' },
      { sourceNodeId: nodes[8].id, targetNodeId: nodes[18].id, relationshipType: 'part_of', weight: 1.0, evidence: 'PD-1 is a key component of the PD-L1/PD-1 checkpoint pathway', source: 'Pathway databases' },
      { sourceNodeId: nodes[9].id, targetNodeId: nodes[14].id, relationshipType: 'associated_with', weight: 0.88, evidence: 'HER2 amplification in 20% of breast cancers', source: 'Clinical data' },
      { sourceNodeId: nodes[6].id, targetNodeId: nodes[15].id, relationshipType: 'activates', weight: 0.90, evidence: 'EGFR activates MAPK/ERK signaling cascade', source: 'KEGG pathway' },
      { sourceNodeId: nodes[6].id, targetNodeId: nodes[16].id, relationshipType: 'activates', weight: 0.88, evidence: 'EGFR activates PI3K/AKT/mTOR pathway', source: 'KEGG pathway' },
      { sourceNodeId: nodes[7].id, targetNodeId: nodes[17].id, relationshipType: 'part_of', weight: 0.95, evidence: 'BCL-2 is a key regulator of the intrinsic apoptosis pathway', source: 'Reactome' },
      { sourceNodeId: nodes[19].id, targetNodeId: nodes[5].id, relationshipType: 'associated_with', weight: 1.0, evidence: 'ABL1 gene encodes the BCR-ABL fusion partner', source: 'NCBI Gene' },
      { sourceNodeId: nodes[20].id, targetNodeId: nodes[6].id, relationshipType: 'associated_with', weight: 1.0, evidence: 'EGFR gene encodes the EGFR protein', source: 'NCBI Gene' },
      { sourceNodeId: nodes[21].id, targetNodeId: nodes[7].id, relationshipType: 'associated_with', weight: 1.0, evidence: 'BCL2 gene encodes BCL-2 protein', source: 'NCBI Gene' },
      { sourceNodeId: nodes[22].id, targetNodeId: nodes[15].id, relationshipType: 'part_of', weight: 0.92, evidence: 'BRAF is a key kinase in the MAPK/ERK pathway', source: 'KEGG pathway' },
      { sourceNodeId: nodes[23].id, targetNodeId: nodes[15].id, relationshipType: 'activates', weight: 0.94, evidence: 'KRAS activates the MAPK/ERK signaling pathway', source: 'Reactome' },
      { sourceNodeId: nodes[24].id, targetNodeId: nodes[17].id, relationshipType: 'activates', weight: 0.91, evidence: 'TP53 activates the apoptosis pathway', source: 'KEGG pathway' },
      { sourceNodeId: nodes[9].id, targetNodeId: nodes[15].id, relationshipType: 'activates', weight: 0.87, evidence: 'HER2 activates MAPK/ERK signaling', source: 'Pathway databases' },
      { sourceNodeId: nodes[9].id, targetNodeId: nodes[16].id, relationshipType: 'activates', weight: 0.85, evidence: 'HER2 activates PI3K/AKT signaling', source: 'Published literature' },
      { sourceNodeId: nodes[0].id, targetNodeId: nodes[10].id, relationshipType: 'associated_with', weight: 0.96, evidence: 'Imatinib is first-line therapy for CML', source: 'Clinical guidelines' },
      { sourceNodeId: nodes[1].id, targetNodeId: nodes[11].id, relationshipType: 'associated_with', weight: 0.82, evidence: 'Erlotinib approved for EGFR-mutant NSCLC', source: 'FDA label' },
      { sourceNodeId: nodes[2].id, targetNodeId: nodes[11].id, relationshipType: 'associated_with', weight: 0.94, evidence: 'Osimertinib for T790M-positive NSCLC', source: 'Clinical trial AURA3' },
      { sourceNodeId: nodes[3].id, targetNodeId: nodes[12].id, relationshipType: 'associated_with', weight: 0.93, evidence: 'Venetoclax approved for CLL', source: 'FDA approval' },
      { sourceNodeId: nodes[4].id, targetNodeId: nodes[13].id, relationshipType: 'associated_with', weight: 0.89, evidence: 'Pembrolizumab approved for advanced melanoma', source: 'KEYNOTE-006 trial' },
      { sourceNodeId: nodes[4].id, targetNodeId: nodes[11].id, relationshipType: 'associated_with', weight: 0.87, evidence: 'Pembrolizumab approved for PD-L1+ NSCLC', source: 'KEYNOTE-024 trial' },
      { sourceNodeId: nodes[22].id, targetNodeId: nodes[13].id, relationshipType: 'associated_with', weight: 0.91, evidence: 'BRAF V600E mutation in 50% of melanomas', source: 'TCGA data' },
      { sourceNodeId: nodes[23].id, targetNodeId: nodes[11].id, relationshipType: 'associated_with', weight: 0.86, evidence: 'KRAS mutations in ~30% of NSCLC', source: 'Genomic studies' },
      { sourceNodeId: nodes[5].id, targetNodeId: nodes[15].id, relationshipType: 'activates', weight: 0.88, evidence: 'BCR-ABL activates MAPK signaling downstream', source: 'Published literature' },
    ]);
    console.log(`Seeded ${edges.length} KnowledgeEdges`);

    // ========== 9. ENTITIES (18) ==========
    const entities = await Entity.bulkCreate([
      { surfaceForm: 'imatinib mesylate', canonicalName: 'Imatinib', entityType: 'chemical', confidence: 0.98, source: 'NER pipeline v2.1', context: 'Imatinib mesylate was administered at 400 mg daily', externalIds: { chemblId: 'CHEMBL941', pubchemCid: '5291' }, resolved: true, resolvedBy: 'ChEMBL lookup' },
      { surfaceForm: 'Gleevec', canonicalName: 'Imatinib', entityType: 'chemical', confidence: 0.95, source: 'NER pipeline v2.1', context: 'Gleevec (imatinib) showed complete cytogenetic response', externalIds: { chemblId: 'CHEMBL941', drugbankId: 'DB00619' }, resolved: true, resolvedBy: 'DrugBank synonym resolution' },
      { surfaceForm: 'EGFR', canonicalName: 'Epidermal Growth Factor Receptor', entityType: 'protein', confidence: 0.99, source: 'NER pipeline v2.1', context: 'EGFR phosphorylation was measured by Western blot', externalIds: { uniprotId: 'P00533', entrezId: '1956' }, resolved: true, resolvedBy: 'UniProt lookup' },
      { surfaceForm: 'ErbB1', canonicalName: 'Epidermal Growth Factor Receptor', entityType: 'protein', confidence: 0.92, source: 'NER pipeline v2.1', context: 'ErbB1 receptor expression was analyzed', externalIds: { uniprotId: 'P00533' }, resolved: true, resolvedBy: 'Gene synonym resolution' },
      { surfaceForm: 'BCR-ABL fusion protein', canonicalName: 'BCR-ABL', entityType: 'protein', confidence: 0.97, source: 'NER pipeline v2.1', context: 'The BCR-ABL fusion protein kinase activity was measured', externalIds: { uniprotId: 'P00519' }, resolved: true, resolvedBy: 'UniProt lookup' },
      { surfaceForm: 'BRCA1', canonicalName: 'BRCA1 DNA Repair Associated', entityType: 'gene', confidence: 0.96, source: 'NER pipeline v2.1', context: 'BRCA1 mutation carriers have increased PARP sensitivity', externalIds: { entrezId: '672', ensemblId: 'ENSG00000012048' }, resolved: true, resolvedBy: 'Ensembl lookup' },
      { surfaceForm: 'TP53', canonicalName: 'Tumor Protein P53', entityType: 'gene', confidence: 0.98, source: 'NER pipeline v2.1', context: 'TP53 mutations were detected in 45% of samples', externalIds: { entrezId: '7157', ensemblId: 'ENSG00000141510' }, resolved: true, resolvedBy: 'NCBI Gene lookup' },
      { surfaceForm: 'KRAS G12C', canonicalName: 'KRAS Proto-Oncogene GTPase', entityType: 'gene', confidence: 0.94, source: 'NER pipeline v2.1', context: 'KRAS G12C mutation was identified by targeted sequencing', externalIds: { entrezId: '3845', cosmicId: 'COSM516' }, resolved: true, resolvedBy: 'COSMIC lookup' },
      { surfaceForm: 'non-small cell lung cancer', canonicalName: 'Non-Small Cell Lung Cancer', entityType: 'disease', confidence: 0.97, source: 'NER pipeline v2.1', context: 'Patients with advanced non-small cell lung cancer were enrolled', externalIds: { meshId: 'D002289', doId: 'DOID:3908' }, resolved: true, resolvedBy: 'MeSH lookup' },
      { surfaceForm: 'NSCLC', canonicalName: 'Non-Small Cell Lung Cancer', entityType: 'disease', confidence: 0.96, source: 'NER pipeline v2.1', context: 'NSCLC accounts for 85% of all lung cancers', externalIds: { meshId: 'D002289' }, resolved: true, resolvedBy: 'Abbreviation resolution' },
      { surfaceForm: 'CML', canonicalName: 'Chronic Myeloid Leukemia', entityType: 'disease', confidence: 0.95, source: 'NER pipeline v2.1', context: 'CML patients with Philadelphia chromosome', externalIds: { meshId: 'D015464' }, resolved: true, resolvedBy: 'MeSH lookup' },
      { surfaceForm: 'vemurafenib', canonicalName: 'Vemurafenib', entityType: 'chemical', confidence: 0.97, source: 'NER pipeline v2.1', context: 'Vemurafenib was tested against BRAF V600E melanoma cells', externalIds: { chemblId: 'CHEMBL1229517' }, resolved: true, resolvedBy: 'ChEMBL lookup' },
      { surfaceForm: 'PD-L1', canonicalName: 'Programmed Death-Ligand 1', entityType: 'protein', confidence: 0.96, source: 'NER pipeline v2.1', context: 'PD-L1 expression was assessed by immunohistochemistry', externalIds: { uniprotId: 'Q9NZQ7' }, resolved: true, resolvedBy: 'UniProt lookup' },
      { surfaceForm: 'sotorasib', canonicalName: 'Sotorasib', entityType: 'chemical', confidence: 0.88, source: 'NER pipeline v2.1', context: 'sotorasib showed activity in KRAS G12C tumors', externalIds: { chemblId: 'CHEMBL4594299' }, resolved: false, resolvedBy: null },
      { surfaceForm: 'CDK4/6', canonicalName: 'Cyclin-Dependent Kinase 4/6', entityType: 'protein', confidence: 0.93, source: 'NER pipeline v2.1', context: 'CDK4/6 inhibitors combined with hormone therapy', externalIds: null, resolved: false, resolvedBy: null },
      { surfaceForm: 'JAK2 V617F', canonicalName: 'Janus Kinase 2', entityType: 'protein', confidence: 0.91, source: 'NER pipeline v2.1', context: 'JAK2 V617F mutation drives myeloproliferative neoplasms', externalIds: { uniprotId: 'O60674' }, resolved: true, resolvedBy: 'UniProt lookup' },
      { surfaceForm: 'H. sapiens', canonicalName: 'Homo sapiens', entityType: 'organism', confidence: 0.99, source: 'NER pipeline v2.1', context: 'Human liver microsomes from H. sapiens donors', externalIds: { ncbiTaxId: '9606' }, resolved: true, resolvedBy: 'NCBI Taxonomy' },
      { surfaceForm: 'IC50 assay', canonicalName: 'Half Maximal Inhibitory Concentration Assay', entityType: 'assay', confidence: 0.90, source: 'NER pipeline v2.1', context: 'IC50 values were determined using dose-response curves', externalIds: null, resolved: false, resolvedBy: null },
    ]);
    console.log(`Seeded ${entities.length} Entities`);

    // ========== 10. PIPELINES (16) ==========
    const pipelines = await Pipeline.bulkCreate([
      { name: 'Mass Spec Raw Data Ingestion', pipelineType: 'ingestion', source: 'Thermo RAW files', destination: 'TetraScience Data Lake', status: 'running', recordsProcessed: 4520, recordsTotal: 5000, startTime: new Date('2026-04-01T08:00:00Z'), endTime: null, errorMessage: null, schedule: '0 */2 * * *', lastRunDuration: 1800, tenantId: tenants[0].id },
      { name: 'HPLC Chromatogram ETL', pipelineType: 'transformation', source: 'Agilent ChemStation', destination: 'PostgreSQL Analytics DB', status: 'completed', recordsProcessed: 1200, recordsTotal: 1200, startTime: new Date('2026-04-01T06:00:00Z'), endTime: new Date('2026-04-01T06:25:00Z'), errorMessage: null, schedule: '0 6 * * *', lastRunDuration: 1500, tenantId: tenants[0].id },
      { name: 'NMR Spectra Processing', pipelineType: 'transformation', source: 'Bruker TopSpin', destination: 'Scientific Data Warehouse', status: 'completed', recordsProcessed: 340, recordsTotal: 340, startTime: new Date('2026-03-31T22:00:00Z'), endTime: new Date('2026-03-31T22:45:00Z'), errorMessage: null, schedule: '0 22 * * *', lastRunDuration: 2700, tenantId: tenants[1].id },
      { name: 'Plate Reader Data Ingestion', pipelineType: 'ingestion', source: 'BMG MARS Export', destination: 'TetraScience Data Lake', status: 'completed', recordsProcessed: 8640, recordsTotal: 8640, startTime: new Date('2026-04-01T09:00:00Z'), endTime: new Date('2026-04-01T09:12:00Z'), errorMessage: null, schedule: '0 9,14 * * 1-5', lastRunDuration: 720, tenantId: tenants[0].id },
      { name: 'Genomic Variant Calling Pipeline', pipelineType: 'transformation', source: 'FASTQ files S3', destination: 'Genomics Analysis DB', status: 'running', recordsProcessed: 15, recordsTotal: 48, startTime: new Date('2026-04-01T00:00:00Z'), endTime: null, errorMessage: null, schedule: '0 0 * * 1', lastRunDuration: 28800, tenantId: tenants[4].id },
      { name: 'ELN Data Export to LIMS', pipelineType: 'export', source: 'Electronic Lab Notebook', destination: 'LabVantage LIMS', status: 'failed', recordsProcessed: 89, recordsTotal: 250, startTime: new Date('2026-04-01T07:00:00Z'), endTime: new Date('2026-04-01T07:15:00Z'), errorMessage: 'Connection timeout to LIMS server after 3 retries. TCP connection refused on port 8443.', schedule: '0 7 * * 1-5', lastRunDuration: 900, tenantId: tenants[0].id },
      { name: 'ChEMBL Compound Sync', pipelineType: 'ingestion', source: 'ChEMBL REST API', destination: 'Molecule Database', status: 'completed', recordsProcessed: 2500, recordsTotal: 2500, startTime: new Date('2026-03-31T01:00:00Z'), endTime: new Date('2026-03-31T01:35:00Z'), errorMessage: null, schedule: '0 1 * * 0', lastRunDuration: 2100, tenantId: tenants[0].id },
      { name: 'Assay Data Validation Pipeline', pipelineType: 'validation', source: 'Raw Assay Results', destination: 'Validated Results Store', status: 'completed', recordsProcessed: 450, recordsTotal: 450, startTime: new Date('2026-04-01T10:00:00Z'), endTime: new Date('2026-04-01T10:08:00Z'), errorMessage: null, schedule: '0 10 * * *', lastRunDuration: 480, tenantId: tenants[0].id },
      { name: 'Flow Cytometry FCS Processing', pipelineType: 'transformation', source: 'BD FACSDiva Export', destination: 'Immunology Data Lake', status: 'paused', recordsProcessed: 0, recordsTotal: 120, startTime: null, endTime: null, errorMessage: 'Pipeline paused: Awaiting instrument recalibration', schedule: '0 */4 * * *', lastRunDuration: null, tenantId: tenants[2].id },
      { name: 'Document Embedding Generation', pipelineType: 'transformation', source: 'Document Store', destination: 'Vector Database', status: 'completed', recordsProcessed: 156, recordsTotal: 156, startTime: new Date('2026-04-01T03:00:00Z'), endTime: new Date('2026-04-01T03:22:00Z'), errorMessage: null, schedule: '0 3 * * *', lastRunDuration: 1320, tenantId: tenants[0].id },
      { name: 'Regulatory Submission Package Export', pipelineType: 'export', source: 'Document Management System', destination: 'FDA eCTD Gateway', status: 'queued', recordsProcessed: 0, recordsTotal: 45, startTime: null, endTime: null, errorMessage: null, schedule: null, lastRunDuration: null, tenantId: tenants[0].id },
      { name: 'Audit Log Archival', pipelineType: 'export', source: 'AuditLog Database', destination: 'S3 Long-Term Archive', status: 'completed', recordsProcessed: 10500, recordsTotal: 10500, startTime: new Date('2026-03-31T02:00:00Z'), endTime: new Date('2026-03-31T02:18:00Z'), errorMessage: null, schedule: '0 2 1 * *', lastRunDuration: 1080, tenantId: tenants[0].id },
      { name: 'Protein Structure PDB Sync', pipelineType: 'ingestion', source: 'RCSB PDB API', destination: 'Structural Biology DB', status: 'failed', recordsProcessed: 12, recordsTotal: 50, startTime: new Date('2026-04-01T04:00:00Z'), endTime: new Date('2026-04-01T04:05:00Z'), errorMessage: 'API rate limit exceeded (429 Too Many Requests). Retry after 3600 seconds.', schedule: '0 4 * * 0', lastRunDuration: 300, tenantId: tenants[1].id },
      { name: 'Clinical Trial Data Integration', pipelineType: 'ingestion', source: 'EDC System (Medidata)', destination: 'Clinical Data Warehouse', status: 'running', recordsProcessed: 3200, recordsTotal: 8000, startTime: new Date('2026-04-01T11:00:00Z'), endTime: null, errorMessage: null, schedule: '0 11 * * 1-5', lastRunDuration: 7200, tenantId: tenants[3].id },
      { name: 'Sequencer Output Processing', pipelineType: 'transformation', source: 'NovaSeq 6000 BCL files', destination: 'FASTQ Storage', status: 'completed', recordsProcessed: 8, recordsTotal: 8, startTime: new Date('2026-03-31T12:00:00Z'), endTime: new Date('2026-03-31T18:00:00Z'), errorMessage: null, schedule: null, lastRunDuration: 21600, tenantId: tenants[4].id },
      { name: 'Data Quality Report Generation', pipelineType: 'validation', source: 'All Data Sources', destination: 'Quality Dashboard', status: 'completed', recordsProcessed: 25000, recordsTotal: 25000, startTime: new Date('2026-04-01T05:00:00Z'), endTime: new Date('2026-04-01T05:30:00Z'), errorMessage: null, schedule: '0 5 * * *', lastRunDuration: 1800, tenantId: tenants[0].id },
    ]);
    console.log(`Seeded ${pipelines.length} Pipelines`);

    // ========== 11. INSTRUMENTS (16) ==========
    const instruments = await Instrument.bulkCreate([
      { name: 'Orbitrap Exploris 480', instrumentType: 'mass_spec', manufacturer: 'Thermo Fisher Scientific', model: 'Exploris 480', serialNumber: 'TF-MS-2024-001', location: 'Building A, Room 204', status: 'online', lastCalibration: new Date('2026-03-15'), nextCalibration: new Date('2026-04-15'), dataFormat: 'RAW', integrationStatus: 'connected', throughputPerDay: 24, tenantId: tenants[0].id },
      { name: 'Q-TOF 6545XT', instrumentType: 'mass_spec', manufacturer: 'Agilent Technologies', model: '6545XT Q-TOF', serialNumber: 'AG-MS-2023-042', location: 'Building A, Room 204', status: 'online', lastCalibration: new Date('2026-03-20'), nextCalibration: new Date('2026-04-20'), dataFormat: 'mzML', integrationStatus: 'connected', throughputPerDay: 48, tenantId: tenants[0].id },
      { name: 'ACQUITY UPLC H-Class', instrumentType: 'hplc', manufacturer: 'Waters Corporation', model: 'ACQUITY H-Class', serialNumber: 'WC-UPLC-2024-003', location: 'Building A, Room 206', status: 'online', lastCalibration: new Date('2026-03-10'), nextCalibration: new Date('2026-04-10'), dataFormat: 'Empower CDS', integrationStatus: 'connected', throughputPerDay: 96, tenantId: tenants[0].id },
      { name: 'Agilent 1260 Infinity II', instrumentType: 'hplc', manufacturer: 'Agilent Technologies', model: '1260 Infinity II', serialNumber: 'AG-HPLC-2023-015', location: 'Building B, Room 102', status: 'maintenance', lastCalibration: new Date('2026-02-28'), nextCalibration: new Date('2026-03-28'), dataFormat: 'ChemStation', integrationStatus: 'disconnected', throughputPerDay: 72, tenantId: tenants[1].id },
      { name: 'Bruker AVANCE NEO 600', instrumentType: 'nmr', manufacturer: 'Bruker BioSpin', model: 'AVANCE NEO 600 MHz', serialNumber: 'BK-NMR-2023-007', location: 'Building A, Room 301', status: 'online', lastCalibration: new Date('2026-03-01'), nextCalibration: new Date('2026-06-01'), dataFormat: 'Bruker TopSpin', integrationStatus: 'connected', throughputPerDay: 12, tenantId: tenants[0].id },
      { name: 'Bruker AVANCE III 400', instrumentType: 'nmr', manufacturer: 'Bruker BioSpin', model: 'AVANCE III 400 MHz', serialNumber: 'BK-NMR-2022-003', location: 'Building B, Room 301', status: 'online', lastCalibration: new Date('2026-03-05'), nextCalibration: new Date('2026-06-05'), dataFormat: 'Bruker TopSpin', integrationStatus: 'connected', throughputPerDay: 16, tenantId: tenants[1].id },
      { name: 'EnVision 2105', instrumentType: 'plate_reader', manufacturer: 'PerkinElmer', model: 'EnVision 2105', serialNumber: 'PE-PR-2024-002', location: 'Building A, Room 108', status: 'online', lastCalibration: new Date('2026-03-25'), nextCalibration: new Date('2026-04-25'), dataFormat: 'CSV/XML', integrationStatus: 'connected', throughputPerDay: 200, tenantId: tenants[0].id },
      { name: 'CLARIOstar Plus', instrumentType: 'plate_reader', manufacturer: 'BMG Labtech', model: 'CLARIOstar Plus', serialNumber: 'BMG-PR-2023-009', location: 'Building A, Room 110', status: 'online', lastCalibration: new Date('2026-03-18'), nextCalibration: new Date('2026-04-18'), dataFormat: 'MARS Export', integrationStatus: 'connected', throughputPerDay: 150, tenantId: tenants[0].id },
      { name: 'BD FACSAria III', instrumentType: 'flow_cytometer', manufacturer: 'BD Biosciences', model: 'FACSAria III', serialNumber: 'BD-FC-2024-001', location: 'Building C, Room 201', status: 'calibrating', lastCalibration: new Date('2026-03-30'), nextCalibration: new Date('2026-04-06'), dataFormat: 'FCS 3.1', integrationStatus: 'pending', throughputPerDay: 30, tenantId: tenants[2].id },
      { name: 'Cytek Aurora', instrumentType: 'flow_cytometer', manufacturer: 'Cytek Biosciences', model: 'Aurora 5L', serialNumber: 'CY-FC-2025-002', location: 'Building C, Room 203', status: 'online', lastCalibration: new Date('2026-03-28'), nextCalibration: new Date('2026-04-28'), dataFormat: 'FCS 3.1', integrationStatus: 'connected', throughputPerDay: 50, tenantId: tenants[2].id },
      { name: 'NovaSeq 6000', instrumentType: 'sequencer', manufacturer: 'Illumina', model: 'NovaSeq 6000', serialNumber: 'IL-SEQ-2024-001', location: 'Building D, Room 101', status: 'online', lastCalibration: new Date('2026-03-01'), nextCalibration: new Date('2026-06-01'), dataFormat: 'BCL/FASTQ', integrationStatus: 'connected', throughputPerDay: 2, tenantId: tenants[4].id },
      { name: 'MiSeq Dx', instrumentType: 'sequencer', manufacturer: 'Illumina', model: 'MiSeq Dx', serialNumber: 'IL-SEQ-2023-008', location: 'Building D, Room 103', status: 'online', lastCalibration: new Date('2026-03-15'), nextCalibration: new Date('2026-06-15'), dataFormat: 'BCL/FASTQ', integrationStatus: 'connected', throughputPerDay: 4, tenantId: tenants[4].id },
      { name: 'Nikon A1R HD25 Confocal', instrumentType: 'microscope', manufacturer: 'Nikon Instruments', model: 'A1R HD25', serialNumber: 'NK-MC-2024-001', location: 'Building C, Room 105', status: 'online', lastCalibration: new Date('2026-03-20'), nextCalibration: new Date('2026-06-20'), dataFormat: 'ND2/TIFF', integrationStatus: 'connected', throughputPerDay: 20, tenantId: tenants[2].id },
      { name: 'Zeiss LSM 980', instrumentType: 'microscope', manufacturer: 'Carl Zeiss', model: 'LSM 980 Airyscan 2', serialNumber: 'CZ-MC-2025-003', location: 'Building C, Room 107', status: 'offline', lastCalibration: new Date('2026-02-15'), nextCalibration: new Date('2026-05-15'), dataFormat: 'CZI/TIFF', integrationStatus: 'disconnected', throughputPerDay: 15, tenantId: tenants[1].id },
      { name: 'Triple Quad 7500', instrumentType: 'mass_spec', manufacturer: 'SCIEX', model: 'Triple Quad 7500', serialNumber: 'SC-MS-2025-001', location: 'Building A, Room 210', status: 'online', lastCalibration: new Date('2026-03-22'), nextCalibration: new Date('2026-04-22'), dataFormat: 'WIFF', integrationStatus: 'connected', throughputPerDay: 60, tenantId: tenants[3].id },
      { name: 'PHERAstar FSX', instrumentType: 'plate_reader', manufacturer: 'BMG Labtech', model: 'PHERAstar FSX', serialNumber: 'BMG-PR-2024-005', location: 'Building A, Room 112', status: 'online', lastCalibration: new Date('2026-03-28'), nextCalibration: new Date('2026-04-28'), dataFormat: 'MARS Export', integrationStatus: 'connected', throughputPerDay: 300, tenantId: tenants[3].id },
    ]);
    console.log(`Seeded ${instruments.length} Instruments`);

    // ========== 12. SEARCH QUERIES (20) ==========
    const searchQueries = await SearchQuery.bulkCreate([
      { query: 'EGFR inhibitor resistance mutations', searchType: 'semantic', resultsCount: 42, clickedResultId: molecules[7].id, clickPosition: 1, responseTimeMs: 245, precisionAtK: 0.85, mrr: 1.0, ndcg: 0.92, userId: users[1].id, sessionId: 'sess-001' },
      { query: 'BCR-ABL kinase IC50 data', searchType: 'keyword', resultsCount: 18, clickedResultId: assays[0].id, clickPosition: 2, responseTimeMs: 120, precisionAtK: 0.78, mrr: 0.5, ndcg: 0.81, userId: users[1].id, sessionId: 'sess-001' },
      { query: 'PARP inhibitor BRCA synthetic lethality', searchType: 'semantic', resultsCount: 35, clickedResultId: molecules[3].id, clickPosition: 1, responseTimeMs: 310, precisionAtK: 0.90, mrr: 1.0, ndcg: 0.95, userId: users[4].id, sessionId: 'sess-002' },
      { query: 'venetoclax BCL-2 CLL clinical data', searchType: 'hybrid', resultsCount: 28, clickedResultId: molecules[8].id, clickPosition: 1, responseTimeMs: 280, precisionAtK: 0.88, mrr: 1.0, ndcg: 0.93, userId: users[1].id, sessionId: 'sess-003' },
      { query: 'mass spectrometry metabolite identification protocol', searchType: 'keyword', resultsCount: 12, clickedResultId: documents[1].id, clickPosition: 1, responseTimeMs: 95, precisionAtK: 0.75, mrr: 1.0, ndcg: 0.88, userId: users[2].id, sessionId: 'sess-004' },
      { query: 'checkpoint immunotherapy PD-1 PD-L1 biomarker', searchType: 'semantic', resultsCount: 56, clickedResultId: documents[6].id, clickPosition: 3, responseTimeMs: 420, precisionAtK: 0.72, mrr: 0.33, ndcg: 0.76, userId: users[4].id, sessionId: 'sess-005' },
      { query: 'KRAS G12C covalent inhibitor', searchType: 'hybrid', resultsCount: 15, clickedResultId: molecules[12].id, clickPosition: 1, responseTimeMs: 195, precisionAtK: 0.82, mrr: 1.0, ndcg: 0.90, userId: users[1].id, sessionId: 'sess-006' },
      { query: 'HTS kinase screening protocol SOP', searchType: 'keyword', resultsCount: 8, clickedResultId: documents[0].id, clickPosition: 1, responseTimeMs: 78, precisionAtK: 0.80, mrr: 1.0, ndcg: 0.89, userId: users[1].id, sessionId: 'sess-007' },
      { query: 'CDK4/6 selective inhibitor breast cancer', searchType: 'semantic', resultsCount: 32, clickedResultId: molecules[17].id, clickPosition: 2, responseTimeMs: 350, precisionAtK: 0.76, mrr: 0.5, ndcg: 0.82, userId: users[4].id, sessionId: 'sess-008' },
      { query: 'flow cytometry immune cell phenotyping', searchType: 'keyword', resultsCount: 14, clickedResultId: documents[7].id, clickPosition: 1, responseTimeMs: 110, precisionAtK: 0.85, mrr: 1.0, ndcg: 0.91, userId: users[3].id, sessionId: 'sess-009' },
      { query: 'drug target interaction prediction machine learning', searchType: 'semantic', resultsCount: 48, clickedResultId: documents[11].id, clickPosition: 1, responseTimeMs: 380, precisionAtK: 0.80, mrr: 1.0, ndcg: 0.88, userId: users[4].id, sessionId: 'sess-010' },
      { query: 'Caco-2 permeability assay results', searchType: 'keyword', resultsCount: 6, clickedResultId: assays[8].id, clickPosition: 1, responseTimeMs: 65, precisionAtK: 0.90, mrr: 1.0, ndcg: 0.94, userId: users[1].id, sessionId: 'sess-011' },
      { query: 'GLP-1 receptor agonist semaglutide mechanism', searchType: 'hybrid', resultsCount: 22, clickedResultId: molecules[6].id, clickPosition: 1, responseTimeMs: 230, precisionAtK: 0.83, mrr: 1.0, ndcg: 0.90, userId: users[1].id, sessionId: 'sess-012' },
      { query: 'BRAF V600E melanoma targeted therapy', searchType: 'semantic', resultsCount: 39, clickedResultId: molecules[2].id, clickPosition: 2, responseTimeMs: 290, precisionAtK: 0.74, mrr: 0.5, ndcg: 0.80, userId: users[4].id, sessionId: 'sess-013' },
      { query: 'hERG toxicity screening cardiac safety', searchType: 'keyword', resultsCount: 11, clickedResultId: assays[9].id, clickPosition: 1, responseTimeMs: 88, precisionAtK: 0.82, mrr: 1.0, ndcg: 0.90, userId: users[1].id, sessionId: 'sess-014' },
      { query: 'NGS library preparation sequencing protocol', searchType: 'keyword', resultsCount: 9, clickedResultId: documents[14].id, clickPosition: 1, responseTimeMs: 72, precisionAtK: 0.78, mrr: 1.0, ndcg: 0.87, userId: users[4].id, sessionId: 'sess-015' },
      { query: 'TRK fusion NTRK inhibitor tumor agnostic', searchType: 'semantic', resultsCount: 25, clickedResultId: molecules[9].id, clickPosition: 1, responseTimeMs: 320, precisionAtK: 0.86, mrr: 1.0, ndcg: 0.93, userId: users[1].id, sessionId: 'sess-016' },
      { query: 'data integrity 21 CFR Part 11 compliance', searchType: 'hybrid', resultsCount: 16, clickedResultId: documents[15].id, clickPosition: 1, responseTimeMs: 175, precisionAtK: 0.88, mrr: 1.0, ndcg: 0.92, userId: users[0].id, sessionId: 'sess-017' },
      { query: 'JAK2 myelofibrosis treatment ruxolitinib', searchType: 'semantic', resultsCount: 20, clickedResultId: molecules[10].id, clickPosition: 1, responseTimeMs: 265, precisionAtK: 0.80, mrr: 1.0, ndcg: 0.89, userId: users[1].id, sessionId: 'sess-018' },
      { query: 'antibody drug conjugate HER2 trastuzumab', searchType: 'hybrid', resultsCount: 31, clickedResultId: molecules[5].id, clickPosition: 2, responseTimeMs: 255, precisionAtK: 0.77, mrr: 0.5, ndcg: 0.83, userId: users[4].id, sessionId: 'sess-019' },
    ]);
    console.log(`Seeded ${searchQueries.length} SearchQueries`);

    // ========== 13. EMBEDDINGS (16) ==========
    const generateFakeVector = (dims: number): string => {
      const vec = Array.from({ length: dims }, () => (Math.random() * 2 - 1).toFixed(6));
      return `[${vec.join(',')}]`;
    };

    const embeddings = await Embedding.bulkCreate([
      { name: 'Imatinib Embedding', sourceText: 'Imatinib mesylate BCR-ABL tyrosine kinase inhibitor CML treatment Gleevec', sourceType: 'molecule', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { moleculeId: molecules[0].id, category: 'small_molecule' }, similarityScore: null },
      { name: 'Erlotinib Embedding', sourceText: 'Erlotinib EGFR epidermal growth factor receptor inhibitor Tarceva NSCLC', sourceType: 'molecule', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { moleculeId: molecules[1].id, category: 'small_molecule' }, similarityScore: null },
      { name: 'Pembrolizumab Embedding', sourceText: 'Pembrolizumab anti-PD-1 checkpoint inhibitor immunotherapy Keytruda melanoma NSCLC', sourceType: 'molecule', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { moleculeId: molecules[4].id, category: 'antibody' }, similarityScore: null },
      { name: 'Venetoclax Embedding', sourceText: 'Venetoclax BCL-2 BH3 mimetic inhibitor CLL AML Venclexta apoptosis', sourceType: 'molecule', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { moleculeId: molecules[8].id, category: 'small_molecule' }, similarityScore: null },
      { name: 'Semaglutide Embedding', sourceText: 'Semaglutide GLP-1 receptor agonist Ozempic Wegovy diabetes obesity peptide', sourceType: 'molecule', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { moleculeId: molecules[6].id, category: 'peptide' }, similarityScore: null },
      { name: 'Osimertinib Embedding', sourceText: 'Osimertinib third generation EGFR T790M resistance mutation Tagrisso NSCLC', sourceType: 'molecule', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { moleculeId: molecules[7].id, category: 'small_molecule' }, similarityScore: null },
      { name: 'TS-001 Embedding', sourceText: 'TS-001 novel KRAS G12C covalent inhibitor screening candidate RAS oncogene', sourceType: 'molecule', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { moleculeId: molecules[12].id, category: 'small_molecule' }, similarityScore: null },
      { name: 'HTS Protocol Embedding', sourceText: 'High-throughput screening protocol kinase inhibitors fluorescence binding assay 384-well plate', sourceType: 'document', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { documentId: documents[0].id, documentType: 'SOP' }, similarityScore: null },
      { name: 'LC-MS SOP Embedding', sourceText: 'LC-MS/MS liquid chromatography mass spectrometry metabolite identification DMPK ADME', sourceType: 'document', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { documentId: documents[1].id, documentType: 'SOP' }, similarityScore: null },
      { name: 'BCR-ABL SAR Review Embedding', sourceText: 'Structure-activity relationships BCR-ABL kinase inhibitors imatinib T315I gatekeeper resistance', sourceType: 'document', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { documentId: documents[5].id, documentType: 'publication' }, similarityScore: null },
      { name: 'Immunotherapy Biomarker Embedding', sourceText: 'Multi-omics biomarker discovery checkpoint immunotherapy PD-1 response prediction transcriptomics proteomics', sourceType: 'document', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { documentId: documents[6].id, documentType: 'publication' }, similarityScore: null },
      { name: 'ML Drug Target Embedding', sourceText: 'Machine learning graph neural networks drug-target interaction prediction BindingDB ChEMBL', sourceType: 'document', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { documentId: documents[11].id, documentType: 'publication' }, similarityScore: null },
      { name: 'BCR-ABL Kinase Assay Embedding', sourceText: 'BCR-ABL kinase IC50 binding assay imatinib validated 25 nM potency', sourceType: 'assay', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { assayId: assays[0].id, assayType: 'binding' }, similarityScore: null },
      { name: 'EGFR Binding Assay Embedding', sourceText: 'EGFR binding assay erlotinib potent inhibition validated kinase activity', sourceType: 'assay', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { assayId: assays[1].id, assayType: 'binding' }, similarityScore: null },
      { name: 'EGFR Entity Embedding', sourceText: 'EGFR epidermal growth factor receptor ErbB1 protein kinase tyrosine phosphorylation', sourceType: 'entity', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { entityId: entities[2].id, entityType: 'protein' }, similarityScore: null },
      { name: 'NSCLC Entity Embedding', sourceText: 'Non-small cell lung cancer NSCLC adenocarcinoma squamous cell carcinoma thoracic oncology', sourceType: 'entity', modelName: 'text-embedding-3-small', dimensions: 384, vector: generateFakeVector(384), metadata: { entityId: entities[8].id, entityType: 'disease' }, similarityScore: null },
    ]);
    console.log(`Seeded ${embeddings.length} Embeddings`);

    // ========== 14. AUDIT LOGS (20) ==========
    const auditLogs = await AuditLog.bulkCreate([
      { action: 'login', resource: 'User', resourceId: users[0].id, userId: users[0].id, userName: 'Alex Thompson', tenantId: tenants[0].id, previousValue: null, newValue: null, ipAddress: '10.0.1.15', userAgent: 'Mozilla/5.0 Chrome/120.0', gxpRelevant: false, electronicSignature: null, reason: null },
      { action: 'login', resource: 'User', resourceId: users[1].id, userId: users[1].id, userName: 'Dr. Maria Santos', tenantId: tenants[0].id, previousValue: null, newValue: null, ipAddress: '10.0.1.22', userAgent: 'Mozilla/5.0 Chrome/120.0', gxpRelevant: false, electronicSignature: null, reason: null },
      { action: 'create', resource: 'Molecule', resourceId: molecules[12].id, userId: users[1].id, userName: 'Dr. Maria Santos', tenantId: tenants[0].id, previousValue: null, newValue: JSON.stringify({ name: 'TS-001', targetProtein: 'KRAS G12C' }), ipAddress: '10.0.1.22', userAgent: 'Mozilla/5.0 Chrome/120.0', gxpRelevant: true, electronicSignature: 'e-sig:santos:2026-03-28', reason: 'New compound registration for KRAS program' },
      { action: 'create', resource: 'AssayResult', resourceId: assays[14].id, userId: users[1].id, userName: 'Dr. Maria Santos', tenantId: tenants[0].id, previousValue: null, newValue: JSON.stringify({ assayName: 'KRAS G12C Covalent Binding', result: 0.45 }), ipAddress: '10.0.1.22', userAgent: 'Mozilla/5.0 Chrome/120.0', gxpRelevant: true, electronicSignature: 'e-sig:santos:2026-03-29', reason: 'Recording KRAS G12C binding assay results' },
      { action: 'update', resource: 'Molecule', resourceId: molecules[12].id, userId: users[1].id, userName: 'Dr. Maria Santos', tenantId: tenants[0].id, previousValue: JSON.stringify({ status: 'screening' }), newValue: JSON.stringify({ status: 'screening', description: 'updated properties' }), ipAddress: '10.0.1.22', userAgent: 'Mozilla/5.0 Chrome/120.0', gxpRelevant: true, electronicSignature: 'e-sig:santos:2026-03-30', reason: 'Updated molecule properties after optimization round' },
      { action: 'read', resource: 'Document', resourceId: documents[8].id, userId: users[0].id, userName: 'Alex Thompson', tenantId: tenants[0].id, previousValue: null, newValue: null, ipAddress: '10.0.1.15', userAgent: 'Mozilla/5.0 Chrome/120.0', gxpRelevant: true, electronicSignature: null, reason: 'Reviewing IND application package' },
      { action: 'create', resource: 'Document', resourceId: documents[8].id, userId: users[0].id, userName: 'Alex Thompson', tenantId: tenants[0].id, previousValue: null, newValue: JSON.stringify({ title: 'IND Application for TS-001', documentType: 'regulatory' }), ipAddress: '10.0.1.15', userAgent: 'Mozilla/5.0 Chrome/120.0', gxpRelevant: true, electronicSignature: 'e-sig:thompson:2026-03-25', reason: 'Creating IND submission package' },
      { action: 'export', resource: 'AssayResult', resourceId: null, userId: users[1].id, userName: 'Dr. Maria Santos', tenantId: tenants[0].id, previousValue: null, newValue: JSON.stringify({ exportType: 'CSV', recordCount: 150 }), ipAddress: '10.0.1.22', userAgent: 'Mozilla/5.0 Chrome/120.0', gxpRelevant: true, electronicSignature: 'e-sig:santos:2026-03-31', reason: 'Exporting assay data for regulatory submission' },
      { action: 'update', resource: 'Pipeline', resourceId: pipelines[5].id, userId: users[2].id, userName: 'James Liu', tenantId: tenants[0].id, previousValue: JSON.stringify({ status: 'running' }), newValue: JSON.stringify({ status: 'failed', errorMessage: 'Connection timeout' }), ipAddress: '10.0.2.10', userAgent: 'Mozilla/5.0 Firefox/121.0', gxpRelevant: false, electronicSignature: null, reason: 'Pipeline failure recorded' },
      { action: 'create', resource: 'Instrument', resourceId: instruments[0].id, userId: users[2].id, userName: 'James Liu', tenantId: tenants[0].id, previousValue: null, newValue: JSON.stringify({ name: 'Orbitrap Exploris 480', status: 'online' }), ipAddress: '10.0.2.10', userAgent: 'Mozilla/5.0 Firefox/121.0', gxpRelevant: true, electronicSignature: 'e-sig:liu:2026-03-15', reason: 'New instrument qualification and registration' },
      { action: 'update', resource: 'Instrument', resourceId: instruments[3].id, userId: users[2].id, userName: 'James Liu', tenantId: tenants[1].id, previousValue: JSON.stringify({ status: 'online' }), newValue: JSON.stringify({ status: 'maintenance' }), ipAddress: '10.0.2.10', userAgent: 'Mozilla/5.0 Firefox/121.0', gxpRelevant: true, electronicSignature: 'e-sig:liu:2026-03-28', reason: 'Instrument taken offline for scheduled maintenance' },
      { action: 'delete', resource: 'SearchQuery', resourceId: null, userId: users[0].id, userName: 'Alex Thompson', tenantId: tenants[0].id, previousValue: JSON.stringify({ count: 50, olderThan: '2025-12-31' }), newValue: null, ipAddress: '10.0.1.15', userAgent: 'Mozilla/5.0 Chrome/120.0', gxpRelevant: false, electronicSignature: null, reason: 'Routine cleanup of old search queries' },
      { action: 'login', resource: 'User', resourceId: users[2].id, userId: users[2].id, userName: 'James Liu', tenantId: tenants[1].id, previousValue: null, newValue: null, ipAddress: '10.0.2.10', userAgent: 'Mozilla/5.0 Firefox/121.0', gxpRelevant: false, electronicSignature: null, reason: null },
      { action: 'create', resource: 'KnowledgeNode', resourceId: nodes[0].id, userId: users[1].id, userName: 'Dr. Maria Santos', tenantId: tenants[0].id, previousValue: null, newValue: JSON.stringify({ label: 'Imatinib', nodeType: 'compound' }), ipAddress: '10.0.1.22', userAgent: 'Mozilla/5.0 Chrome/120.0', gxpRelevant: false, electronicSignature: null, reason: 'Building knowledge graph for BCR-ABL program' },
      { action: 'create', resource: 'Entity', resourceId: entities[0].id, userId: users[4].id, userName: 'Prof. Kenji Tanaka', tenantId: tenants[4].id, previousValue: null, newValue: JSON.stringify({ surfaceForm: 'imatinib mesylate', entityType: 'chemical' }), ipAddress: '10.0.5.8', userAgent: 'Mozilla/5.0 Safari/17.2', gxpRelevant: false, electronicSignature: null, reason: 'NER pipeline entity extraction' },
      { action: 'update', resource: 'AssayResult', resourceId: assays[0].id, userId: users[1].id, userName: 'Dr. Maria Santos', tenantId: tenants[0].id, previousValue: JSON.stringify({ status: 'pending' }), newValue: JSON.stringify({ status: 'validated' }), ipAddress: '10.0.1.22', userAgent: 'Mozilla/5.0 Chrome/120.0', gxpRelevant: true, electronicSignature: 'e-sig:santos:2026-03-20', reason: 'Validating BCR-ABL IC50 assay results after peer review' },
      { action: 'export', resource: 'Document', resourceId: documents[8].id, userId: users[0].id, userName: 'Alex Thompson', tenantId: tenants[0].id, previousValue: null, newValue: JSON.stringify({ exportType: 'PDF', destination: 'FDA eCTD' }), ipAddress: '10.0.1.15', userAgent: 'Mozilla/5.0 Chrome/120.0', gxpRelevant: true, electronicSignature: 'e-sig:thompson:2026-04-01', reason: 'Exporting IND package for FDA submission' },
      { action: 'login', resource: 'User', resourceId: users[4].id, userId: users[4].id, userName: 'Prof. Kenji Tanaka', tenantId: tenants[4].id, previousValue: null, newValue: null, ipAddress: '10.0.5.8', userAgent: 'Mozilla/5.0 Safari/17.2', gxpRelevant: false, electronicSignature: null, reason: null },
      { action: 'read', resource: 'Molecule', resourceId: molecules[0].id, userId: users[3].id, userName: 'Rachel Green', tenantId: tenants[2].id, previousValue: null, newValue: null, ipAddress: '10.0.3.5', userAgent: 'Mozilla/5.0 Edge/120.0', gxpRelevant: false, electronicSignature: null, reason: null },
      { action: 'logout', resource: 'User', resourceId: users[0].id, userId: users[0].id, userName: 'Alex Thompson', tenantId: tenants[0].id, previousValue: null, newValue: null, ipAddress: '10.0.1.15', userAgent: 'Mozilla/5.0 Chrome/120.0', gxpRelevant: false, electronicSignature: null, reason: null },
    ]);
    console.log(`Seeded ${auditLogs.length} AuditLogs`);

    console.log('\n========================================');
    console.log('Seed completed successfully!');
    console.log('========================================');
    console.log(`Tenants:         ${tenants.length}`);
    console.log(`Roles:           ${roles.length}`);
    console.log(`Users:           ${users.length}`);
    console.log(`Molecules:       ${molecules.length}`);
    console.log(`AssayResults:    ${assays.length}`);
    console.log(`Documents:       ${documents.length}`);
    console.log(`KnowledgeNodes:  ${nodes.length}`);
    console.log(`KnowledgeEdges:  ${edges.length}`);
    console.log(`Entities:        ${entities.length}`);
    console.log(`Pipelines:       ${pipelines.length}`);
    console.log(`Instruments:     ${instruments.length}`);
    console.log(`SearchQueries:   ${searchQueries.length}`);
    console.log(`Embeddings:      ${embeddings.length}`);
    console.log(`AuditLogs:       ${auditLogs.length}`);
    console.log('========================================\n');

    process.exit(0);
  } catch (error) {
    console.error('Seed failed:', error);
    process.exit(1);
  }
}

seed();
